export const worldTagKeys = {
  abandonedColony: 'abandonedColony',
  alienRuins: 'alienRuins',
  alteredHumanity: 'alteredHumanity',
  anarchists: 'anarchists',
  anthropomorphs: 'anthropomorphs',
  area51: 'area51',
  badlandsWorld: 'badlandsWorld',
  battleground: 'battleground',
  beastmasters: 'beastmasters',
  bubbleCities: 'bubbleCities',
  cheapLife: 'cheapLife',
  civilWar: 'civilWar',
  coldWar: 'coldWar',
  colonizedPopulation: 'colonizedPopulation',
  culturalPower: 'culturalPower',
  cybercommunists: 'cybercommunists',
  cyborgs: 'cyborgs',
  cyclicalDoom: 'cyclicalDoom',
  desertWorld: 'desertWorld',
  doomedWorld: 'doomedWorld',
  dyingRace: 'dyingRace',
  eugenicCult: 'eugenicCult',
  exchangeConsulate: 'exchangeConsulate',
  fallenHegemon: 'fallenHegemon',
  feralWorld: 'feralWorld',
  flyingCities: 'flyingCities',
  forbiddenTech: 'forbiddenTech',
  formerWarriors: 'formerWarriors',
  freakGeology: 'freakGeology',
  freakWeather: 'freakWeather',
  friendlyFoe: 'friendlyFoe',
  goldRush: 'goldRush',
  greatWork: 'greatWork',
  hatred: 'hatred',
  heavyIndustry: 'heavyIndustry',
  heavyMining: 'heavyMining',
  hivemind: 'hivemind',
  holyWar: 'holyWar',
  hostileBiosphere: 'hostileBiosphere',
  hostileSpace: 'hostileSpace',
  immortals: 'immortals',
  localSpecialty: 'localSpecialty',
  localTech: 'localTech',
  majorSpaceyard: 'majorSpaceyard',
  mandarinate: 'mandarinate',
  mandateBase: 'mandateBase',
  maneaters: 'maneaters',
  megacorps: 'megacorps',
  mercenaries: 'mercenaries',
  minimalContact: 'minimalContact',
  misandryMisogyny: 'misandryMisogyny',
  nightWorld: 'nightWorld',
  nomads: 'nomads',
  oceanicWorld: 'oceanicWorld',
  outOfContact: 'outOfContact',
  outpostWorld: 'outpostWorld',
  perimeterAgency: 'perimeterAgency',
  pilgrimageSite: 'pilgrimageSite',
  pleasureWorld: 'pleasureWorld',
  policeState: 'policeState',
  postScarcity: 'postScarcity',
  preceptorArchive: 'preceptorArchive',
  pretechCultists: 'pretechCultists',
  primitiveAliens: 'primitiveAliens',
  prisonPlanet: 'prisonPlanet',
  psionicsAcademy: 'psionicsAcademy',
  psionicsFear: 'psionicsFear',
  psionicsWorship: 'psionicsWorship',
  quarantinedWorld: 'quarantinedWorld',
  radioactiveWorld: 'radioactiveWorld',
  refugees: 'refugees',
  regionalHegemon: 'regionalHegemon',
  restrictiveLaws: 'restrictiveLaws',
  revanchists: 'revanchists',
  revolutionaries: 'revolutionaries',
  rigidCulture: 'rigidCulture',
  risingHegemon: 'risingHegemon',
  ritualCombat: 'ritualCombat',
  robots: 'robots',
  seagoingCities: 'seagoingCities',
  sealedMenace: 'sealedMenace',
  secretMasters: 'secretMasters',
  sectarians: 'sectarians',
  seismicInstability: 'seismicInstability',
  shackledWorld: 'shackledWorld',
  societalDespair: 'societalDespair',
  soleSupplier: 'soleSupplier',
  tabooTreasure: 'tabooTreasure',
  terraformFailure: 'terraformFailure',
  theocracy: 'theocracy',
  tombWorld: 'tombWorld',
  tradeHub: 'tradeHub',
  tyranny: 'tyranny',
  unbrakedAi: 'unbrakedAi',
  urbanizedSurface: 'urbanizedSurface',
  utopia: 'utopia',
  warlords: 'warlords',
  xenophiles: 'xenophiles',
  xenophobes: 'xenophobes',
  zombies: 'zombies',
};

export default {
    [worldTagKeys.abandonedColony]: {
    key: worldTagKeys.abandonedColony,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
   [worldTagKeys.alienRuins]: {
    key: worldTagKeys.alienRuins,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 4,
    places: 4,
  },
  [worldTagKeys.alteredHumanity]: {
    key: worldTagKeys.alteredHumanity,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 4,
    places: 3,
  },
  [worldTagKeys.anarchists]: {
    key: worldTagKeys.anarchists,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.anthropomorphs]: {
    key: worldTagKeys.anthropomorphs,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.area51]: {
    key: worldTagKeys.area51,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.badlandsWorld]: {
    key: worldTagKeys.badlandsWorld,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.battleground]: {
    key: worldTagKeys.battleground,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.beastmasters]: {
    key: worldTagKeys.beastmasters,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.bubbleCities]: {
    key: worldTagKeys.bubbleCities,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 4,
  },
  [worldTagKeys.cheapLife]: {
    key: worldTagKeys.cheapLife,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.civilWar]: {
    key: worldTagKeys.civilWar,
    enemies: 5,
    friends: 3,
    complications: 3,
    things: 4,
    places: 4,
  },
  [worldTagKeys.coldWar]: {
    key: worldTagKeys.coldWar,
    enemies: 3,
    friends: 4,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.colonizedPopulation]: {
    key: worldTagKeys.colonizedPopulation,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.culturalPower]: {
    key: worldTagKeys.culturalPower,
    enemies: 4,
    friends: 4,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.cybercommunists]: {
    key: worldTagKeys.cybercommunists,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.cyborgs]: {
    key: worldTagKeys.cyborgs,
    enemies: 4,
    friends: 3,
    complications: 3,
    things: 4,
    places: 3,
  },
  [worldTagKeys.cyclicalDoom]: {
    key: worldTagKeys.cyclicalDoom,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.desertWorld]: {
    key: worldTagKeys.desertWorld,
    enemies: 5,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.doomedWorld]: {
    key: worldTagKeys.doomedWorld,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 4,
    places: 3,
  },
  [worldTagKeys.dyingRace]: {
    key: worldTagKeys.dyingRace,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.eugenicCult]: {
    key: worldTagKeys.eugenicCult,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 4,
    places: 3,
  },
  [worldTagKeys.exchangeConsulate]: {
    key: worldTagKeys.exchangeConsulate,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.fallenHegemon]: {
    key: worldTagKeys.fallenHegemon,
    enemies: 4,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.feralWorld]: {
    key: worldTagKeys.feralWorld,
    enemies: 5,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.flyingCities]: {
    key: worldTagKeys.flyingCities,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.forbiddenTech]: {
    key: worldTagKeys.forbiddenTech,
    enemies: 3,
    friends: 4,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.formerWarriors]: {
    key: worldTagKeys.formerWarriors,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.freakGeology]: {
    key: worldTagKeys.freakGeology,
    enemies: 2,
    friends: 3,
    complications: 3,
    things: 3,
    places: 2,
  },
  [worldTagKeys.freakWeather]: {
    key: worldTagKeys.freakWeather,
    enemies: 3,
    friends: 2,
    complications: 2,
    things: 3,
    places: 3,
  },
  [worldTagKeys.friendlyFoe]: {
    key: worldTagKeys.friendlyFoe,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.goldRush]: {
    key: worldTagKeys.goldRush,
    enemies: 4,
    friends: 4,
    complications: 3,
    things: 3,
    places: 4,
  },
  [worldTagKeys.greatWork]: {
    key: worldTagKeys.greatWork,
    enemies: 4,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.hatred]: {
    key: worldTagKeys.hatred,
    enemies: 2,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.heavyIndustry]: {
    key: worldTagKeys.heavyIndustry,
    enemies: 4,
    friends: 3,
    complications: 4,
    things: 3,
    places: 4,
  },
  [worldTagKeys.heavyMining]: {
    key: worldTagKeys.heavyMining,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.hivemind]: {
    key: worldTagKeys.hivemind,
    enemies: 3,
    friends: 3,
    complications: 5,
    things: 3,
    places: 3,
  },
  [worldTagKeys.holyWar]: {
    key: worldTagKeys.holyWar,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.hostileBiosphere]: {
    key: worldTagKeys.hostileBiosphere,
    enemies: 4,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.hostileSpace]: {
    key: worldTagKeys.hostileSpace,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.immortals]: {
    key: worldTagKeys.immortals,
    enemies: 3,
    friends: 2,
    complications: 5,
    things: 3,
    places: 3,
  },
  [worldTagKeys.localSpecialty]: {
    key: worldTagKeys.localSpecialty,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.localTech]: {
    key: worldTagKeys.localTech,
    enemies: 4,
    friends: 3,
    complications: 4,
    things: 4,
    places: 3,
  },
  [worldTagKeys.majorSpaceyard]: {
    key: worldTagKeys.majorSpaceyard,
    enemies: 4,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.mandarinate]: {
    key: worldTagKeys.mandarinate,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.mandateBase]: {
    key: worldTagKeys.mandateBase,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.maneaters]: {
    key: worldTagKeys.maneaters,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.megacorps]: {
    key: worldTagKeys.megacorps,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 4,
    places: 3,
  },
  [worldTagKeys.mercenaries]: {
    key: worldTagKeys.mercenaries,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.minimalContact]: {
    key: worldTagKeys.minimalContact,
    enemies: 3,
    friends: 4,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.misandryMisogyny]: {
    key: worldTagKeys.misandryMisogyny,
    enemies: 3,
    friends: 4,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.nightWorld]: {
    key: worldTagKeys.nightWorld,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.nomads]: {
    key: worldTagKeys.nomads,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.oceanicWorld]: {
    key: worldTagKeys.oceanicWorld,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 4,
  },
  [worldTagKeys.outOfContact]: {
    key: worldTagKeys.outOfContact,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.outpostWorld]: {
    key: worldTagKeys.outpostWorld,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 4,
  },
  [worldTagKeys.perimeterAgency]: {
    key: worldTagKeys.perimeterAgency,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 4,
  },
  [worldTagKeys.pilgrimageSite]: {
    key: worldTagKeys.pilgrimageSite,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.pleasureWorld]: {
    key: worldTagKeys.pleasureWorld,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.policeState]: {
    key: worldTagKeys.policeState,
    enemies: 3,
    friends: 4,
    complications: 3,
    things: 3,
    places: 4,
  },
  [worldTagKeys.postScarcity]: {
    key: worldTagKeys.postScarcity,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.preceptorArchive]: {
    key: worldTagKeys.preceptorArchive,
    enemies: 4,
    friends: 4,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.pretechCultists]: {
    key: worldTagKeys.pretechCultists,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.primitiveAliens]: {
    key: worldTagKeys.primitiveAliens,
    enemies: 4,
    friends: 4,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.prisonPlanet]: {
    key: worldTagKeys.prisonPlanet,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.psionicsAcademy]: {
    key: worldTagKeys.psionicsAcademy,
    enemies: 4,
    friends: 3,
    complications: 5,
    things: 3,
    places: 4,
  },
  [worldTagKeys.psionicsFear]: {
    key: worldTagKeys.psionicsFear,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.psionicsWorship]: {
    key: worldTagKeys.psionicsWorship,
    enemies: 4,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.quarantinedWorld]: {
    key: worldTagKeys.quarantinedWorld,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },

  
  
  [worldTagKeys.radioactiveWorld]: {
    key: worldTagKeys.radioactiveWorld,
    name: 'Radioactive World',
    description:
      'Whether due to a legacy of atomic warfare unhindered by nuke snuffers or a simple profusion of radioactive elements, this world glows in the dark. Even heavy vacc suits can filter only so much of the radiation, and most natives suffer a wide variety of cancers, mutations and other illnesses without the protection of advanced medical treatments.',
    'misc.enemies': [
      'bitter mutant',
      'relic warlord',
      'desperate would be escapee',
    ],
    'misc.friends': [
      'reckless prospector',
      'offworld scavenger',
      'biogenetic variety seeker',
    ],
    'misc.complications': [
      'the radioactivity is steadily growing worse',
      "the planet's medical resources break down",
      'the radioactivity has inexplicable effects on living creatures',
      'the radioactivity is the product of a malfunctioning pretech manufactory',
    ],
    'misc.things': [
      'ancient atomic weaponry',
      'pretech anti-radioactivity drugs',
      'untainted water supply',
    ],
    'misc.places': [
      'mutant-infested ruins',
      'scorched glass plain',
      'wilderness of bizarre native life',
      'glowing barrens',
    ],
  },
  [worldTagKeys.refugees]: {
    key: worldTagKeys.refugees,
    name: 'Refugees',
    description:
      'The world teems with refugees, either exiles from another planet who managed to get here, or the human detritus of some local conflict that have fled to the remaining stable states. The natives usually regard the refugees with hostility, an attitude returned by many among their unwilling guests.',
    'misc.enemies': [
      'xenophobic native leader',
      'refugee chief aspiring to seize the host nation',
      'politician seeking to use the refugees as a weapon',
    ],
    'misc.friends': [
      'sympathetic refugee waif',
      'local hard-pressed by refugee gangs',
      'clergy seeking peace',
    ],
    'misc.complications': [
      'the xenophobes are right that the refugees are taking over',
      'the refugees are right that the xenophobes want them out or dead',
      'both are right',
      'outside powers are using hte refugees to destabalize an enemy government',
      'refugee and local cultures are extremely incompatible',
    ],
    'misc.things': [
      'treasures brought out by fleeing refugees',
      'citizenship papers',
      'cache of vital refugee supplies',
      'hidden arms for terrorists',
    ],
    'misc.places': [
      'hopeless refugee camp',
      'city swarming with confused strangers',
      'festival full of angry locals',
    ],
  },
  [worldTagKeys.regionalHegemon]: {
    key: worldTagKeys.regionalHegemon,
    name: 'Regional Hegemon',
    description:
      'This world has the technological sophistication, natural resources, and determined polity necessary to be a regional hegemon for the sector. Nearby worlds are likely either directly subservient to it or tack carefully to avoid its anger. It may even be the capital of a small stellar empire.',
    'misc.enemies': [
      'ambitious general',
      'colonial official',
      'contemptuous noble',
    ],
    'misc.friends': ['diplomat', 'offworld ambassador', 'foreign spy'],
    'misc.complications': [
      "the hegemon's influence is all that's keeping a murderous war from breaking out on nearby worlds",
      'the hegemon is decaying and losing its control',
      'the government is riddled with spies',
      'the hegemon is genuinely benign',
    ],
    'misc.things': [
      'diplomat carte blanche',
      'deed to an offworld estate',
      'foreign aid grant',
    ],
    'misc.places': [
      'palace or seat of government',
      'salon teeming with spies',
      'protets rally',
      'military base',
    ],
  },
  [worldTagKeys.restrictiveLaws]: {
    key: worldTagKeys.restrictiveLaws,
    name: 'Restrictive Laws',
    description:
      'A myriad of laws, customs, and rules constrain the inhabitants of this world, and even acts that are completely permissible elsewhere are punished severely here. The locals may provide lists of these laws to offworlders, but few non-natives can hope to master all the important intricacies.',
    'misc.enemies': [
      'law enforcement officer',
      'outraged native',
      'native lawyer specializing in peeling offworlders',
      'paid snitch',
    ],
    'misc.friends': [
      'frustrated offworlder',
      'repressed native',
      'reforming crusader',
    ],
    'misc.complications': [
      'the laws chnage regularly in patterns only natives understand',
      'the laws forbid some action vital to the party',
      'the laws forbid the simple existence of some party members',
      'the laws are secret to offworlders',
    ],
    'misc.things': [
      'complete legal codex',
      'writ of diplomatic immunity',
      'fine collection of vault contents',
    ],
    'misc.places': [
      'courtroom',
      'mob scene of outraged locals',
      'legislative chamber',
      'police station',
    ],
  },
  [worldTagKeys.revanchists]: {
    key: worldTagKeys.revanchists,
    name: 'Revanchists',
    description:
      "The locals formerly owned another world, or a major nation on the planet formerly owned an additional region of land. Something happened to take away this control or drive out the former rulers, and they've never forgotten it. The locals are obsessed with reclaiming their lost lands, and will allow no questions of practicality to interfere with their cause.",
    'misc.enemies': [
      'demagogue whipping the locals on to a hopeless war',
      'politician seeking to use the resentment for their own ends',
      'local convinced the PCs are agents of the "thieving" power',
      'refugee from the land bitterly demanding it be reclaimed',
    ],
    'misc.friends': [
      'realist local clergy seeking peace',
      'olitician trying to calm the public',
      'third-party diplomat trying to stamp out the fire',
    ],
    'misc.complications': [
      "the revanchists' claim is completely just and reasonable",
      'the land is now occupied entirely by heirs of the conquerors',
      'both sides have seized lands the other thinks are theirs',
    ],
    'misc.things': [
      'stock of vital resource produced by the taken land',
      'relic carried out of it',
      'proof that the land claim is justified or unjustified',
    ],
    'misc.places': [
      'memorial monument to the loss',
      'cemetery of those who died in the conquest',
      'public ceremony commemorating the disaster',
    ],
  },
  [worldTagKeys.revolutionaries]: {
    key: worldTagKeys.revolutionaries,
    name: 'Revolutionaries',
    description:
      'The world is convulsed by one or more bands of revolutionaries, with some nations perhaps in the grip of a current revolution. Most of these upheavals can be expected only to change the general flavor of problems in the polity, but the process of getting there usually produces a tremendous amount of suffering.',
    'misc.enemies': [
      'blood-drenched revolutionary leader',
      'blood-drenched secret police chief',
      'hostile foreign agent seeking further turmoil',
    ],
    'misc.friends': [
      'sympathetic victim accused of revolutionary sympathies or government collaboration',
      'revolutionary or state agent who now repents',
      'agent of a neutral power that wants peace',
    ],
    'misc.complications': [
      'the revolutionaries actually do seem likely to put in better rulers',
      'the revolutionaries are client groups that got out of hand',
      'the revolutionaries are clearly much worse than the government',
      'the revolutionaries have no real ideals beyond power and merely pretend to ideology',
    ],
    'misc.things': [
      'list of secret revolutionary sympathizers',
      'proof of rebel hypocrisy',
      'confiscated wealth',
    ],
    'misc.places': [
      'festival that explodes into violence',
      'heavily-fortified police station',
      'revolutionary base hidden in the wilderness',
    ],
  },
  [worldTagKeys.rigidCulture]: {
    key: worldTagKeys.rigidCulture,
    name: 'Rigid Culture',
    description:
      'The local culture is extremely rigid. Certain forms of behavior and belief are absolutely mandated, and any deviation from these principles is punished, or else society may be strongly stratified by birth with limited prospects for change. Anything which threatens the existing social order is feared and shunned.',
    'misc.enemies': [
      'rigid reactionary',
      'wary ruler',
      'regime ideologue',
      'offended potentate',
    ],
    'misc.friends': [
      'revolutionary agitator',
      'ambitious peasant',
      'frustrated merchant',
    ],
    'misc.complications': [
      'the cultural patterns are enforced by technological aids',
      'the culture is run by a secret cabal of manipulators',
      'the culture has explicit religious sanction',
      'the culture evolved due to important necessities that have since been forgotten',
    ],
    'misc.things': [
      'precious traditional regalia',
      'peasant tribute',
      'opulent trasures of the ruling class',
    ],
    'misc.places': [
      'time-worn palace',
      'low caste slums',
      'bandit den',
      'reformist temple',
    ],
  },
  [worldTagKeys.risingHegemon]: {
    key: worldTagKeys.risingHegemon,
    name: 'Rising Hegemon',
    description:
      "This world is not yet a dominant power in the sector, but it's well on its way there. Whether through newly-blossoming economic, military, or cultural power, they're extending their influence over their neighbors and forging new arrangements between their government and the rulers of nearby worlds.",
    'misc.enemies': [
      'jingoistic supremacist',
      'official bent on glorious success',
      'foreign agent saboteur',
    ],
    'misc.friends': [
      'friendly emissary to the benighted',
      'hardscrabble local turned great success',
      'foreign visitor seeking contracts or knowledge',
    ],
    'misc.complications': [
      "they're only strong because their neighbors have been weakened",
      'their success is based on a fluke resource or pretech find',
      'they bitterly resent their neighbors as former oppressors',
    ],
    'misc.things': [
      'tribute shipment',
      'factory or barracks emblematic of their power source',
      'tech or data that will deal a blow to their rise',
    ],
    'misc.places': [
      'rustic town being hurled into prosperity',
      'government building being expanded',
      'starport struggling under the flow of new ships',
    ],
  },
  [worldTagKeys.ritualCombat]: {
    key: worldTagKeys.ritualCombat,
    name: 'Ritual Combat',
    description:
      "The locals favor some form of stylized combat to resolve disputes, provide entertainment, or settle religious differences. This combat is probably not normally lethal unless it's reserved for a specific disposable class of slaves or professionals. Some combat may involve mastery of esoteric weapons and complex arenas, while other forms might require nothing more than a declaration in the street and a drawn gun.",
    'misc.enemies': [
      'bloodthirsty local champion',
      'ambitious gladiator stable owner',
      'xenophobic master fighter',
    ],
    'misc.friends': [
      'peace-minded foreign missionary',
      'temperate defender of the weak',
      'local eager to learn of offworld fighting styles',
    ],
    'misc.complications': [
      'The required weapons are strange pretech artifacts',
      'certain classes are forbidden from fighting and require champions',
      "loss doesn't mean death but it does mean ritual scarring or property loss",
    ],
    'misc.things': [
      'magnificent weapon',
      'secret book of martial techniques',
      'token signifying immunity to ritual combat challenges',
      'prize won in bloody battle',
    ],
    'misc.places': [
      'area full of cheering spectators',
      'dusty street outside a saloon',
      'memorial for fallen warriors',
    ],
  },
  [worldTagKeys.robots]: {
    key: worldTagKeys.robots,
    name: 'Robots',
    description:
      'The world has a great many robots on it. Most bots are going to be non-sentient expert systems, though an AI with enough computing resources can control many bots at once, and some worlds may have developed VIs to a degree that individual bots can seem (or be) sentient. Some worlds might even be ruled by metal overlords, ones which do not need to be sentient so long as they have overwhelming force.',
    'misc.enemies': [
      'hostile robot master',
      'robot greedy to seize offworld tech',
      "robot fallen in love with the PC's ship",
      'oligarch whose factories build robots',
    ],
    'misc.friends': [
      'data-seeking robot',
      'plucky young robot tech',
      'local being pushed out of a job by robots',
    ],
    'misc.complications': [
      'the robots are only partially controlled',
      'the robots are salvaged and originally meant for a much darker use',
      'the robots require a rare material that the locals fight over',
      "the robots require the planet's specific infrastructure so cannot be exported",
    ],
    'misc.things': [
      'prototype robot',
      'secret robot override codes',
      'vast cache of robot-made goods',
      'robot-destroying pretech weapon',
    ],
    'misc.places': [
      'humming robotic factory',
      'stark robotic "barracks"',
      'house crowded with robot servants and only one human owner',
    ],
  },
  [worldTagKeys.seagoingCities]: {
    key: worldTagKeys.seagoingCities,
    name: 'Seagoing Cities',
    description:
      'Either the world is entirely water or else the land is simply too dangerous for most humans. Human settlement on this world consists of a number of floating cities that follow the currents and the fish. These city-ships might have been purpose-built for their task, or they could be jury-rigged conglomerations of ships and structures thrown together when the need for seagoing life become apparent to the locals.',
    'misc.enemies': [
      'pirate city lord',
      'mer-human raider chieftain',
      'hostile landsman noble',
      'enemy city saboteur',
    ],
    'misc.friends': [
      'city navigator',
      'scout captain',
      'curious mer-human',
      'hard-pressed ship-city engineer',
    ],
    'misc.complications': [
      'the seas are not water',
      'the fish schools have vanished and the city faces starvation',
      'terrible storms drive the city into the glacial regions',
      "suicide ships ram the city's hull",
    ],
    'misc.things': [
      'giant pearls with mysterious chemical properties',
      'buried treasure',
      'vital repair materials',
    ],
    'misc.places': [
      'Bridge of the city',
      'storm-tossed sea',
      'a bridge fashioned of many small boats',
    ],
  },
  [worldTagKeys.sealedMenace]: {
    key: worldTagKeys.sealedMenace,
    name: 'Sealed Menace',
    description:
      'Something on this planet has the potential to create enormous havoc for the inhabitants if it is not kept safely contained by its keepers. Whether a massive seismic fault line suppressed by pretech terraforming technology, a disease that has to be quarantined within hours of discovery, or an ancient alien relic that requires regular upkeep in order to prevent planetary catastrophe, the menace is a constant shadow on the fearful populace.',
    'misc.enemies': [
      'hostile outsider bent on freeing the menace',
      'misguided fool who thinks he can use it',
      'reckless researcher who thinks he can fix it',
    ],
    'misc.friends': [
      'keeper of the menace',
      'student of its nature',
      'victim of the menace',
    ],
    'misc.complications': [
      'the menace would bring great wealth along with destruction',
      'the menace is intelligent',
      "the natives don't all believe in the menace",
    ],
    'misc.things': [
      'a key to unlock the menace',
      'a precious byproduct of the menace',
      "the secret of the menace's true nature",
    ],
    'misc.places': [
      'guarded fortress containing the menace',
      'monitoring station',
      'scene of a prior outbreak of the menace',
    ],
  },
  [worldTagKeys.secretMasters]: {
    key: worldTagKeys.secretMasters,
    name: 'Secret Masters',
    description:
      "The world is actually run by a hidden cabal, acting through their catspaws in the visible government. For one reason or another, this group finds it imperative that they not be identified by outsiders, and in some cases even the planet's own government may not realize that they're actually being manipulated by hidden masters.",
    'misc.enemies': [
      'an agent of the cabal',
      'government official who wants no questions asked',
      'willfully blinded local',
    ],
    'misc.friends': [
      'paranoid conspiracy theorist',
      'machiavellian gamesman within the cabal',
      'interstellar investigator',
    ],
    'misc.complications': [
      'the secret masters have a benign reason for wanting secrecy',
      'the cabal fights openly amongst itself',
      'the cabal is recruiting new members',
    ],
    'misc.things': [
      'a dossier of secrets on a government official',
      'a briefcase of unmarked credit notes',
      'the identity of a cabal member',
    ],
    'misc.places': [
      'smoke-filled room',
      'shadowy alleyway',
      'secret underground bunker',
    ],
  },
  [worldTagKeys.sectarians]: {
    key: worldTagKeys.sectarians,
    name: 'Sectarians',
    description:
      'The world is torn by violent disagreement between sectarians of a particular faith. Each views the other as a damnable heresy in need of extirpation. Local government may be able to keep open war from breaking out, but the poisonous hatred divides communities. The nature of the faith may be religious, or it may be based on some secular ideology.',
    'misc.enemies': [
      'paranoid believer',
      'native convinced the party is working for the other side',
      'absolutist ruler',
    ],
    'misc.friends': [
      'reformist clergy',
      'local peacekeeping official',
      'offworld missionary',
      'exhausted ruler',
    ],
    'misc.complications': [
      'the conflict has more than two sides',
      'the sectarians hate each other for multiple reasons',
      'the sectarians must cooperate or else life on this world is imperiled',
      'the sectarians hate outsiders more than they hate each other',
      'the differences in sects are incomprehensible to an outsider',
    ],
    'misc.things': [
      'ancient holy book',
      'incontrovertible proof',
      'offering to a local holy man',
    ],
    'misc.places': [
      'sectarian battlefield',
      'crusading temple',
      "philosopher's salon",
      'bitterly divided village',
    ],
  },
  [worldTagKeys.seismicInstability]: {
    key: worldTagKeys.seismicInstability,
    name: 'Seismic Instability',
    description:
      'The local land masses are remarkably unstable, and regular earthquakes rack the surface. Local construction is either advanced enough to sway and move with the vibrations or primitive enough that it is easily rebuilt. Severe volcanic activity may be part of the instability.',
    'misc.enemies': [
      'earthquake cultist',
      'hermit seismologist',
      'burrowing native life form',
      'earthquake-inducing saboteur',
    ],
    'misc.friends': [
      'experimental construction firm owner',
      'adventurous volcanologist',
      'geothermal prospector',
    ],
    'misc.complications': [
      'the earthquakes are caused by malfunctioning pretech terraformers',
      "they're caused by alien technology",
      "they're restrained by alien technology that is being plundered by offworlders",
      'the earthquakes are used to generate enormous amounts of energy',
    ],
    'misc.things': [
      'earthquake generator',
      'earthquake suppressor',
      'mineral formed at the core of the world',
      'earthquake-proof building schematics',
    ],
    'misc.places': [
      'volcanic caldera',
      'village during an earthquake',
      'mud slide',
      'earthquake opening superheated steam fissures',
    ],
  },
  [worldTagKeys.shackledWorld]: {
    key: worldTagKeys.shackledWorld,
    name: 'Shackled World',
    description:
      'This world is being systematically contained by an outside power. Some ancient autonomous defense grid, robot law enforcement, alien artifact, or other force is preventing the locals from developing certain technology, or using certain devices, or perhaps from developing interstellar flight. This limit may or may not apply to offworlders; in the former case, the PCs may have to figure out a way to beat the shackles simply to escape the world.',
    'misc.enemies': [
      'passionless jailer-AI',
      'paranoid military grid AI',
      'robot overlord',
      'enigmatic alien master',
    ],
    'misc.friends': [
      'struggling local researcher',
      'offworlder trapped here',
      'scientist with a plan to break the chains',
    ],
    'misc.complications': [
      'the shackles come off for certain brief windows of time',
      'the locals think the shackles are imposed by God',
      'an outside power greatly profits from the shackles',
      'the rulers are exempt from the shackles',
    ],
    'misc.things': [
      'keycode to bypass the shackle',
      'tech shielded from the shackle',
      'exportable version of the shackle that can affect other worlds',
    ],
    'misc.places': [
      'grim high-tech control center',
      'factory full of workaround tech',
      'temple to the power or entity that imposed the shackle',
    ],
  },
  [worldTagKeys.societalDespair]: {
    key: worldTagKeys.societalDespair,
    name: 'Societal Despair',
    description:
      "The world's dominant society has lost faith in itself. Whether through some all-consuming war, great catastrophe, overwhelming outside culture, or religious collapse, the natives no longer believe in their old values, and search desperately for something new. Fierce conflict often exists between the last believers in the old dispensation and the nihilistic or searching disciples of the new age.",
    'misc.enemies': [
      'zealot who blames outsiders for the decay',
      'nihilistic warlord',
      'offworlder looking to exploit the local despair',
    ],
    'misc.friends': [
      'struggling messenger of a new way',
      'valiant paragon of a fading tradition',
      'local going through the motions of serving a now-irrelevant role',
    ],
    'misc.complications': [
      'a massive war discredited all the old values',
      'outside powers are working to erode societal confidence for their own benefit',
      'a local power is profiting greatly from the despair',
      'the old ways were meant to aid survival on this world and their passing is causing many new woes',
    ],
    'misc.things': [
      'relic that would inspire a renaissance',
      'art that would inspire new ideas',
      'priceless artifact of a now-scorned belief',
    ],
    'misc.places': [
      'empty temple',
      'crowded den of obliviating vice',
      'smoky hall full of frantic speakers',
    ],
  },
  [worldTagKeys.soleSupplier]: {
    key: worldTagKeys.soleSupplier,
    name: 'Sole Supplier',
    description:
      "Some extremely important resource is exported from this world and this world alone. It's unlikely that the substance is critical for building spike drives unless this world is also the first to begin interstellar flight, but it may be critical to other high-tech processes or devices. The locals make a large amount of money off this trade and control of it is of critical importance to the planet's rulers, and potentially to outside powers.",
    'misc.enemies': [
      'resource oligarch, Ruthless smuggler',
      'resource-controlling warlord',
      'foreign agent seeking to subvert local government',
    ],
    'misc.friends': [
      'doughty resource miner',
      'researcher trying to synthesize the stuff',
      'small-scale resource producer',
      'harried starport trade overseer',
    ],
    'misc.complications': [
      'the substance is slow poison to process',
      'the substance is created by hostile alien natives',
      'the substance is very easy to smuggle in usable amounts',
      'only the natives have the genes or tech to extract it effectively',
    ],
    'misc.things': [
      'cache of processed resource',
      'trade permit to buy a load of it',
      'a shipment of nigh-undetectably fake substance',
    ],
    'misc.places': [
      'bustling resource extraction site',
      'opulent palace built with resource money',
      'lazy town square where everyone lives on resource payments',
    ],
  },
  [worldTagKeys.tabooTreasure]: {
    key: worldTagKeys.tabooTreasure,
    name: 'Taboo Treasure',
    description:
      'The natives here produce something that is both fabulously valuable and strictly forbidden elsewhere in the sector. It may be a lethally addictive drug, forbidden gengineering tech, vat-grown "perfect slaves", or a useful substance that can only be made through excruciating human suffering. This treasure is freely traded on the world, but bringing it elsewhere is usually an invitation to a long prison stay or worse.',
    'misc.enemies': [
      'maker of a vile commodity',
      'smuggler for a powerful offworlder',
      'depraved offworlder here for "fun"',
      'local warlord who controls the treasure',
    ],
    'misc.friends': [
      'reformer seeking to end its use',
      'innovator trying to repurpose the treasure in innocent ways',
      'wretched addict unwillingly prey to the treasure',
    ],
    'misc.complications': [
      'the treasure is extremely hard to smuggle',
      'its use visibly marks a user',
      'the natives consider it for their personal use only',
    ],
    'misc.things': [
      'load of the forbidden good',
      'smuggling tech that could hide the good perfectly',
      'blackmail data on offworld buyers of the good',
    ],
    'misc.places': [
      'den where the good is used',
      'market selling the good to locals and a few outsiders',
      'factory or processing area where the good is created',
    ],
  },
  [worldTagKeys.terraformFailure]: {
    key: worldTagKeys.terraformFailure,
    name: 'Terraform Failure',
    description:
      "This world was marginal for human habitation when it was discovered, but the Mandate or the early government put in pretech terraforming engines to correct its more extreme qualities. The terraforming did not entirely work, either failing of its own or suffering the destruction of the engines during the Silence. The natives are only partly adapted to the world's current state, and struggle with the environment.",
    'misc.enemies': [
      'brutal ruler who cares only for their people',
      'offworlder trying to loot the damaged engines',
      'warlord trying to seize limited habitable land',
    ],
    'misc.friends': [
      'local trying to fix the engines',
      'offworlder student of the engines',
      'world-wise native survivor',
    ],
    'misc.complications': [
      'the engines produced too much of something instead of too little',
      'the engines were hijacked by aliens with different preferences',
      'it was discovered that an Earth-like environment would eventually cause a catastrophic disaster',
    ],
    'misc.things': [
      'parts to repair or restore the engines',
      'lootable pretech fragments',
      'valuable local tech devised to cope with the world',
    ],
    'misc.places': [
      'zone of tolerable gravity or temperature',
      'native settlement built to cope with the environment',
      'massive ruined terraforming engine',
    ],
  },
  [worldTagKeys.theocracy]: {
    key: worldTagKeys.theocracy,
    name: 'Theocracy',
    description:
      'The planet is ruled by the priesthood of the predominant religion or ideology. The rest of the locals may or may not be terribly pious, but the clergy have the necessary military strength, popular support or control of resources to maintain their rule. Alternative faiths or incompatible ideologies are likely to be both illegal and socially unacceptable.',
    'misc.enemies': [
      'decadent priest-ruler',
      'zealous inquisitor',
      'relentless proselytizer',
      'True Believer',
    ],
    'misc.friends': [
      'heretic',
      'offworld theologian',
      'atheistic merchant',
      'desperate commoner',
    ],
    'misc.complications': [
      'the theocracy actually works well',
      'the theocracy is decadent and hated by the common folk',
      'the theocracy is divided into mutually hostile sects',
      'the theocracy is led by aliens',
    ],
    'misc.things': [
      'precious holy text',
      "martyr's bones",
      'secret church records',
      'ancient church treasures',
    ],
    'misc.places': [
      'glorious temple',
      'austere monastery',
      'academy for ideological indoctrination',
      'decadent pleasure-cathedral',
    ],
  },
  [worldTagKeys.tombWorld]: {
    key: worldTagKeys.tombWorld,
    name: 'Tomb World',
    description:
      'Tomb worlds are planets that were once inhabited by humans before the Silence. The sudden collapse of the jump gate network and the inability to bring in the massive food supplies required by the planet resulted in starvation, warfare, and death. Most tomb worlds are naturally hostile to human habitation and could not raise sufficient crops to maintain life. The few hydroponic facilities were usually destroyed in the fighting, and all that is left now are ruins, bones, and silence.',
    'misc.enemies': [
      'demented survivor tribe chieftain',
      'avaricious scavenger',
      'automated defense system',
      'native predator',
    ],
    'misc.friends': [
      'scavenger fleet captain',
      'archaeologist',
      'salvaging historian',
      'xenophilic native survivor',
    ],
    'misc.complications': [
      'the ruins are full of booby-traps left by the final inhabitants',
      "the world's atmosphere quickly degrades anything in an opened building",
      'a handful of desperate natives survived the Silence',
      'the structures are unstable and collapsing',
    ],
    'misc.things': [
      'lost pretech equipment',
      'tech caches',
      'stores of unused munitions',
      'ancient historical data',
    ],
    'misc.places': [
      'crumbling hive-city',
      'city square carpeted in bones',
      'ruined hydroponic facility',
      "cannibal tribe's lair",
      'dead orbital jump gate',
    ],
  },
  [worldTagKeys.tradeHub]: {
    key: worldTagKeys.tradeHub,
    name: 'Trade Hub',
    description:
      'This world is a major crossroads for local interstellar trade. It is well-positioned at the nexus of several short-drill trade routes, and has facilities for easy transfer of valuable cargoes and the fueling and repairing of starships. The natives are accustomed to outsiders, and a polyglot mass of people from every nearby world can be found trading here.',
    'misc.enemies': [
      'cheating merchant',
      'thieving dockworker',
      'commercial spy',
      'corrupt customs official',
    ],
    'misc.friends': [
      'rich tourist',
      'hardscrabble free trader',
      'merchant prince in need of catspaws',
      'friendly spaceport urchin',
    ],
    'misc.complications': [
      'an outworlder faction schemes to seize the trade hub',
      "saboteurs seek to blow up a rival's warehouses",
      'enemies are blockading the trade routes',
      'pirates lace the hub with spies',
    ],
    'misc.things': [
      "voucher for a warehouse's contents",
      'insider trading information',
      'case of precious offworld pharmaceuticals',
      'box of legitimate tax stamps indicating customs dues have been paid',
    ],
    'misc.places': [
      'raucous bazaar',
      'elegant restaurant',
      'spaceport teeming with activity',
      'foggy street lined with warehouses',
    ],
  },
  [worldTagKeys.tyranny]: {
    key: worldTagKeys.tyranny,
    name: 'Tyranny',
    description:
      'The local government is brutal and indifferent to the will of the people. Laws may or may not exist, but the only one that matters is the whim of the rulers on any given day. Their minions swagger through the streets while the common folk live in terror of their appetites. The only people who stay wealthy are friends and servants of the ruling class.',
    'misc.enemies': [
      'debauched autocrat',
      'sneering bully-boy',
      'soulless government official',
      'occupying army officer',
    ],
    'misc.friends': [
      'conspiring rebel',
      'oppressed merchant',
      'desperate peasant',
      'inspiring religious leader',
    ],
    'misc.complications': [
      'the tyrant rules with vastly superior technology',
      'the tyrant is a figurehead for a cabal of powerful men and women',
      'the people are resigned to their suffering',
      'the tyrant is hostile to “meddlesome outworlders”',
    ],
    'misc.things': [
      'plundered wealth',
      'beautiful toys of the elite',
      'regalia of rulership',
    ],
    'misc.places': [
      'impoverished village',
      'protest rally massacre',
      'decadent palace',
      'religious hospital for the indigent',
    ],
  },
  [worldTagKeys.unbrakedAi]: {
    key: worldTagKeys.unbrakedAi,
    name: 'Unbraked AI',
    description:
      'Artificial intelligences are costly and difficult to create, requiring a careful sequence of “growth stages” in order to bring them to sentience before artificial limits on cognition speed and learning development are installed. These “brakes” prevent runaway cognition metastasis. This world has an “unbraked AI” on it, probably with a witting or unwitting corps of servants. Unbraked AIs are quite insane, but they learn and reason with a speed impossible for humans, and can demonstrate a truly distressing subtlety.',
    'misc.enemies': [
      'AI cultist',
      'maltech researcher',
      'government official dependent on the AI',
    ],
    'misc.friends': ['perimeter agent', 'AI researcher', 'braked AI'],
    'misc.complications': [
      "the AI's presence is unknown to the locals",
      'the locals depend on the AI for some vital service',
      'the AI appears to be harmless',
      "the AI has fixated on the group's ship's computer",
      'the AI wants transport offworld',
    ],
    'misc.things': [
      'the room-sized AI core itself',
      'maltech research files',
      'perfectly tabulated blackmail on government officials',
      'pretech computer circuitry',
    ],
    'misc.places': [
      'municipal computing banks',
      'cult compound',
      'repair center',
      'ancient hardcopy library',
    ],
  },
  [worldTagKeys.urbanizedSurface]: {
    key: worldTagKeys.urbanizedSurface,
    name: 'Urbanized Surface',
    description:
      "The world's land area is covered with buildings that extend downward for multiple levels. Such worlds either have a population in the trillions, extremely little land area, or are largely-abandoned due to some past catastrophe. Agriculture and resource extraction are part of the urban complex, and there may be an advanced maintenance system that may not be entirely under the control of present natives.",
    'misc.enemies': [
      'maintenance AI that hates outsiders',
      'tyrant of a habitation block',
      'deep-dwelling prophet who considers "the sky" a blasphemy to be quelled',
    ],
    'misc.friends': [
      'local yearning for wild spaces',
      'grubby urchin of the underlevels',
      'harried engineer trying to maintain ancient works',
      'grizzled hab cop',
    ],
    'misc.complications': [
      'the urban blocks are needed to survive the environment',
      'the blocks were part of an ancient device of world-spanning size',
      'the blocks require constant maintenance to avoid dangerous types of decay',
    ],
    'misc.things': [
      'massively efficient power source',
      'map of the secret ways of a zone',
      'passkey into restricted hab block areas',
    ],
    'misc.places': [
      'giant hab block now devoid of inhabitants',
      'chemical-reeking underway',
      'seawater mine full of salt and massive flowing channels',
    ],
  },
  [worldTagKeys.utopia]: {
    key: worldTagKeys.utopia,
    name: 'Utopia',
    description:
      'Natural and social conditions on this world have made it a paradise for its inhabitants, a genuine utopia of happiness and fulfillment. This is normally the result of drastic human engineering, including brain-gelding, neurochemical control, personality curbs, or complete "humanity" redefinitions. Even so, the natives are extremely happy with their lot, and may wish to extend that joy to poor, sad outsiders.',
    'misc.enemies': [
      'compassionate neurotherapist',
      'proselytizing native missionary to outsiders',
      'brutal tyrant who rules through inexorable happiness',
    ],
    'misc.friends': [
      'deranged malcontent',
      'bloody-handed guerilla leader of a rebellion of madmen',
      'outsider trying to find a way to reverse the utopian changes',
    ],
    'misc.complications': [
      'the natives really are deeply and contentedly happy with their altered lot',
      'the utopia produces something that attracts others',
      'the utopia works on converting outsiders through persuasion and generosity',
      "the utopia involves some sacrifice that's horrifying to non-members",
    ],
    'misc.things': [
      'portable device that applies the utopian change',
      'plans for a device that would destroy the utopia',
      'goods created joyfully by the locals',
    ],
    'misc.places': [
      'plaza full of altered humans',
      'social ritual site',
      'secret office where "normal" humans rule',
    ],
  },
  [worldTagKeys.warlords]: {
    key: worldTagKeys.warlords,
    name: 'Warlords',
    description:
      'The world is plagued by warlords. Numerous powerful men and women control private armies sufficiently strong to cow whatever local government may exist. On the lands they claim, their word is law. Most spend their time oppressing their own subjects and murderously pillaging those of their neighbors. Most like to wrap themselves in the mantle of ideology, religious fervor, or an ostensibly legitimate right to rule.',
    'misc.enemies': [
      'warlord',
      'avaricious lieutenant',
      'expensive assassin',
      'aspiring minion',
    ],
    'misc.friends': [
      'Vengeful commoner',
      'government military officer',
      'humanitarian aid official',
      'village priest',
    ],
    'misc.complications': [
      'the warlords are willing to cooperate to fight mutual threats',
      'the warlords favor specific religions or races over others',
      'the warlords are using substantially more sophisticated tech than others',
      'some of the warlords are better rulers than the government',
    ],
    'misc.things': [
      'weapons cache, Buried plunder',
      "a warlord's personal battle harness",
      'captured merchant shipping',
    ],
    'misc.places': [
      'gory battlefield',
      'burnt-out village',
      'barbaric warlord palace',
      'squalid refugee camp',
    ],
  },
  [worldTagKeys.xenophiles]: {
    key: worldTagKeys.xenophiles,
    name: 'Xenophiles',
    description:
      'The natives of this world are fast friends with a particular alien race. The aliens may have saved the planet at some point in the past, or awed the locals with superior tech or impressive cultural qualities. The aliens might even be the ruling class on the planet.',
    'misc.enemies': [
      'offworld xenophobe',
      'suspicious alien leader',
      'xenocultural imperialist',
    ],
    'misc.friends': [
      'benevolent alien',
      'native malcontent',
      'gone-native offworlder',
    ],
    'misc.complications': [
      'the enthusiasm is due to alien psionics or tech',
      'the enthusiasm is based on a lie, The aliens strongly dislike their “groupies”',
      'the aliens feel obliged to rule humanity for its own good',
      'humans badly misunderstand the aliens',
    ],
    'misc.things': [
      'hybrid alien-human tech',
      'exotic alien crafts',
      'sophisticated xenolinguistic and xenocultural research data',
    ],
    'misc.places': [
      'alien district',
      'alien-influenced human home',
      'cultural festival celebrating alien artist',
    ],
  },
  [worldTagKeys.xenophobes]: {
    key: worldTagKeys.xenophobes,
    name: 'Xenophobes',
    description:
      'The natives are intensely averse to dealings with outworlders. Whether through cultural revulsion, fear of tech contamination, or a genuine immunodeficiency, the locals shun foreigners from offworld and refuse to have anything to do with them beyond the bare necessities of contact. Trade may or may not exist on this world, but if it does, it is almost certainly conducted by a caste of untouchables and outcasts.',
    'misc.enemies': [
      'revulsed local ruler',
      'native convinced some wrong was done to him',
      'cynical demagogue',
    ],
    'misc.friends': [
      'curious native',
      'exiled former ruler',
      'local desperately seeking outworlder help',
    ],
    'misc.complications': [
      'the natives are symptomless carriers of a contagious and dangerous disease',
      'the natives are exceptionally vulnerable to offworld diseases',
      'the natives require elaborate purification rituals after speaking to an offworlder or touching them',
      'the local ruler has forbidden any mercantile dealings with outworlders',
    ],
    'misc.things': [
      'jealously-guarded precious relic',
      'local product under export ban',
      'esoteric local technology',
    ],
    'misc.places': [
      'sealed treaty port',
      'public ritual not open to outsiders',
      'outcaste slum home',
    ],
  },
  [worldTagKeys.zombies]: {
    key: worldTagKeys.zombies,
    name: 'Zombies',
    description:
      'This menace may not take the form of shambling corpses, but some disease, alien artifact, or crazed local practice produces men and women with habits similar to those of murderous cannibal undead. These outbreaks may be regular elements in local society, either provoked by some malevolent creators or the consequence of some local condition.',
    'misc.enemies': [
      'soulless maltech biotechnology cult',
      'sinister governmental agent',
      'crazed zombie cultist',
    ],
    'misc.friends': [
      'survivor of an outbreak',
      'doctor searching for a cure',
      'rebel against the secret malefactors',
    ],
    'misc.complications': [
      'the zombies retain human intelligence',
      'the zombies can be cured',
      'the process is voluntary among devotees',
      'the condition is infectious',
    ],
    'misc.things': [
      'cure for the condition',
      'alien artifact that causes it',
      "details of the cult's conversion process",
    ],
    'misc.places': [
      'house with boarded-up windows',
      'dead city',
      'fortified bunker that was overrun from within',
    ],
  },
};
