export const worldTagKeys = {
  abandonedColony: 'abandonedColony',
  alienRuins: 'alienRuins',
  alteredHumanity: 'alteredHumanity',
  anarchists: 'anarchists',
  anthropomorphs: 'anthropomorphs',
  area51: 'area51',
  badlandsWorld: 'badlandsWorld',
  battleground: 'battleground',
  beastmasters: 'beastmasters',
  bubbleCities: 'bubbleCities',
  cheapLife: 'cheapLife',
  civilWar: 'civilWar',
  coldWar: 'coldWar',
  colonizedPopulation: 'colonizedPopulation',
  culturalPower: 'culturalPower',
  cybercommunists: 'cybercommunists',
  cyborgs: 'cyborgs',
  cyclicalDoom: 'cyclicalDoom',
  desertWorld: 'desertWorld',
  doomedWorld: 'doomedWorld',
  dyingRace: 'dyingRace',
  eugenicCult: 'eugenicCult',
  exchangeConsulate: 'exchangeConsulate',
  fallenHegemon: 'fallenHegemon',
  feralWorld: 'feralWorld',
  flyingCities: 'flyingCities',
  forbiddenTech: 'forbiddenTech',
  formerWarriors: 'formerWarriors',
  freakGeology: 'freakGeology',
  freakWeather: 'freakWeather',
  friendlyFoe: 'friendlyFoe',
  goldRush: 'goldRush',
  greatWork: 'greatWork',
  hatred: 'hatred',
  heavyIndustry: 'heavyIndustry',
  heavyMining: 'heavyMining',
  hivemind: 'hivemind',
  holyWar: 'holyWar',
  hostileBiosphere: 'hostileBiosphere',
  hostileSpace: 'hostileSpace',
  immortals: 'immortals',
  localSpecialty: 'localSpecialty',
  localTech: 'localTech',
  majorSpaceyard: 'majorSpaceyard',
  mandarinate: 'mandarinate',
  mandateBase: 'mandateBase',
  maneaters: 'maneaters',
  megacorps: 'megacorps',
  mercenaries: 'mercenaries',
  minimalContact: 'minimalContact',
  misandryMisogyny: 'misandryMisogyny',
  nightWorld: 'nightWorld',
  nomads: 'nomads',
  oceanicWorld: 'oceanicWorld',
  outOfContact: 'outOfContact',
  outpostWorld: 'outpostWorld',
  perimeterAgency: 'perimeterAgency',
  pilgrimageSite: 'pilgrimageSite',
  pleasureWorld: 'pleasureWorld',
  policeState: 'policeState',
  postScarcity: 'postScarcity',
  preceptorArchive: 'preceptorArchive',
  pretechCultists: 'pretechCultists',
  primitiveAliens: 'primitiveAliens',
  prisonPlanet: 'prisonPlanet',
  psionicsAcademy: 'psionicsAcademy',
  psionicsFear: 'psionicsFear',
  psionicsWorship: 'psionicsWorship',
  quarantinedWorld: 'quarantinedWorld',
  radioactiveWorld: 'radioactiveWorld',
  refugees: 'refugees',
  regionalHegemon: 'regionalHegemon',
  restrictiveLaws: 'restrictiveLaws',
  revanchists: 'revanchists',
  revolutionaries: 'revolutionaries',
  rigidCulture: 'rigidCulture',
  risingHegemon: 'risingHegemon',
  ritualCombat: 'ritualCombat',
  robots: 'robots',
  seagoingCities: 'seagoingCities',
  sealedMenace: 'sealedMenace',
  secretMasters: 'secretMasters',
  sectarians: 'sectarians',
  seismicInstability: 'seismicInstability',
  shackledWorld: 'shackledWorld',
  societalDespair: 'societalDespair',
  soleSupplier: 'soleSupplier',
  tabooTreasure: 'tabooTreasure',
  terraformFailure: 'terraformFailure',
  theocracy: 'theocracy',
  tombWorld: 'tombWorld',
  tradeHub: 'tradeHub',
  tyranny: 'tyranny',
  unbrakedAi: 'unbrakedAi',
  urbanizedSurface: 'urbanizedSurface',
  utopia: 'utopia',
  warlords: 'warlords',
  xenophiles: 'xenophiles',
  xenophobes: 'xenophobes',
  zombies: 'zombies',
};

export default {
    [worldTagKeys.abandonedColony]: {
    key: worldTagKeys.abandonedColony,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
   [worldTagKeys.alienRuins]: {
    key: worldTagKeys.alienRuins,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 4,
    places: 4,
  },
  [worldTagKeys.alteredHumanity]: {
    key: worldTagKeys.alteredHumanity,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 4,
    places: 3,
  },
  [worldTagKeys.anarchists]: {
    key: worldTagKeys.anarchists,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.anthropomorphs]: {
    key: worldTagKeys.anthropomorphs,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.area51]: {
    key: worldTagKeys.area51,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.badlandsWorld]: {
    key: worldTagKeys.badlandsWorld,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.battleground]: {
    key: worldTagKeys.battleground,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.beastmasters]: {
    key: worldTagKeys.beastmasters,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.bubbleCities]: {
    key: worldTagKeys.bubbleCities,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 4,
  },
  [worldTagKeys.cheapLife]: {
    key: worldTagKeys.cheapLife,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.civilWar]: {
    key: worldTagKeys.civilWar,
    enemies: 5,
    friends: 3,
    complications: 3,
    things: 4,
    places: 4,
  },
  [worldTagKeys.coldWar]: {
    key: worldTagKeys.coldWar,
    enemies: 3,
    friends: 4,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.colonizedPopulation]: {
    key: worldTagKeys.colonizedPopulation,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.culturalPower]: {
    key: worldTagKeys.culturalPower,
    enemies: 4,
    friends: 4,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.cybercommunists]: {
    key: worldTagKeys.cybercommunists,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.cyborgs]: {
    key: worldTagKeys.cyborgs,
    enemies: 4,
    friends: 3,
    complications: 3,
    things: 4,
    places: 3,
  },
  [worldTagKeys.cyclicalDoom]: {
    key: worldTagKeys.cyclicalDoom,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.desertWorld]: {
    key: worldTagKeys.desertWorld,
    enemies: 5,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.doomedWorld]: {
    key: worldTagKeys.doomedWorld,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 4,
    places: 3,
  },
  [worldTagKeys.dyingRace]: {
    key: worldTagKeys.dyingRace,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.eugenicCult]: {
    key: worldTagKeys.eugenicCult,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 4,
    places: 3,
  },
  [worldTagKeys.exchangeConsulate]: {
    key: worldTagKeys.exchangeConsulate,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.fallenHegemon]: {
    key: worldTagKeys.fallenHegemon,
    enemies: 4,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.feralWorld]: {
    key: worldTagKeys.feralWorld,
    enemies: 5,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.flyingCities]: {
    key: worldTagKeys.flyingCities,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.forbiddenTech]: {
    key: worldTagKeys.forbiddenTech,
    enemies: 3,
    friends: 4,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.formerWarriors]: {
    key: worldTagKeys.formerWarriors,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.freakGeology]: {
    key: worldTagKeys.freakGeology,
    enemies: 2,
    friends: 3,
    complications: 3,
    things: 3,
    places: 2,
  },
  [worldTagKeys.freakWeather]: {
    key: worldTagKeys.freakWeather,
    enemies: 3,
    friends: 2,
    complications: 2,
    things: 3,
    places: 3,
  },
  [worldTagKeys.friendlyFoe]: {
    key: worldTagKeys.friendlyFoe,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.goldRush]: {
    key: worldTagKeys.goldRush,
    enemies: 4,
    friends: 4,
    complications: 3,
    things: 3,
    places: 4,
  },
  [worldTagKeys.greatWork]: {
    key: worldTagKeys.greatWork,
    enemies: 4,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.hatred]: {
    key: worldTagKeys.hatred,
    enemies: 2,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.heavyIndustry]: {
    key: worldTagKeys.heavyIndustry,
    enemies: 4,
    friends: 3,
    complications: 4,
    things: 3,
    places: 4,
  },
  [worldTagKeys.heavyMining]: {
    key: worldTagKeys.heavyMining,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.hivemind]: {
    key: worldTagKeys.hivemind,
    enemies: 3,
    friends: 3,
    complications: 5,
    things: 3,
    places: 3,
  },
  [worldTagKeys.holyWar]: {
    key: worldTagKeys.holyWar,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.hostileBiosphere]: {
    key: worldTagKeys.hostileBiosphere,
    enemies: 4,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.hostileSpace]: {
    key: worldTagKeys.hostileSpace,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.immortals]: {
    key: worldTagKeys.immortals,
    enemies: 3,
    friends: 2,
    complications: 5,
    things: 3,
    places: 3,
  },
  [worldTagKeys.localSpecialty]: {
    key: worldTagKeys.localSpecialty,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.localTech]: {
    key: worldTagKeys.localTech,
    enemies: 4,
    friends: 3,
    complications: 4,
    things: 4,
    places: 3,
  },
  [worldTagKeys.majorSpaceyard]: {
    key: worldTagKeys.majorSpaceyard,
    enemies: 4,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.mandarinate]: {
    key: worldTagKeys.mandarinate,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.mandateBase]: {
    key: worldTagKeys.mandateBase,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.maneaters]: {
    key: worldTagKeys.maneaters,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.megacorps]: {
    key: worldTagKeys.megacorps,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 4,
    places: 3,
  },
  [worldTagKeys.mercenaries]: {
    key: worldTagKeys.mercenaries,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.minimalContact]: {
    key: worldTagKeys.minimalContact,
    enemies: 3,
    friends: 4,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.misandryMisogyny]: {
    key: worldTagKeys.misandryMisogyny,
    enemies: 3,
    friends: 4,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.nightWorld]: {
    key: worldTagKeys.nightWorld,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.nomads]: {
    key: worldTagKeys.nomads,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.oceanicWorld]: {
    key: worldTagKeys.oceanicWorld,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 4,
  },
  [worldTagKeys.outOfContact]: {
    key: worldTagKeys.outOfContact,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.outpostWorld]: {
    key: worldTagKeys.outpostWorld,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 4,
  },
  [worldTagKeys.perimeterAgency]: {
    key: worldTagKeys.perimeterAgency,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 4,
  },
  [worldTagKeys.pilgrimageSite]: {
    key: worldTagKeys.pilgrimageSite,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.pleasureWorld]: {
    key: worldTagKeys.pleasureWorld,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.policeState]: {
    key: worldTagKeys.policeState,
    enemies: 3,
    friends: 4,
    complications: 3,
    things: 3,
    places: 4,
  },
  [worldTagKeys.postScarcity]: {
    key: worldTagKeys.postScarcity,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.preceptorArchive]: {
    key: worldTagKeys.preceptorArchive,
    enemies: 4,
    friends: 4,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.pretechCultists]: {
    key: worldTagKeys.pretechCultists,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.primitiveAliens]: {
    key: worldTagKeys.primitiveAliens,
    enemies: 4,
    friends: 4,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.prisonPlanet]: {
    key: worldTagKeys.prisonPlanet,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.psionicsAcademy]: {
    key: worldTagKeys.psionicsAcademy,
    enemies: 4,
    friends: 3,
    complications: 5,
    things: 3,
    places: 4,
  },
  [worldTagKeys.psionicsFear]: {
    key: worldTagKeys.psionicsFear,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.psionicsWorship]: {
    key: worldTagKeys.psionicsWorship,
    enemies: 4,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.quarantinedWorld]: {
    key: worldTagKeys.quarantinedWorld,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.radioactiveWorld]: {
    key: worldTagKeys.radioactiveWorld,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 4,
  },
  [worldTagKeys.refugees]: {
    key: worldTagKeys.refugees,
    enemies: 3,
    friends: 3,
    complications: 5,
    things: 4,
    places: 3,
  },
  [worldTagKeys.regionalHegemon]: {
    key: worldTagKeys.regionalHegemon,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 4,
  },
  [worldTagKeys.restrictiveLaws]: {
    key: worldTagKeys.restrictiveLaws,
    enemies: 4,
    friends: 3,
    complications: 4,
    things: 3,
    places: 4,
  },
  [worldTagKeys.revanchists]: {
    key: worldTagKeys.revanchists,
    enemies: 4,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.revolutionaries]: {
    key: worldTagKeys.revolutionaries,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.rigidCulture]: {
    key: worldTagKeys.rigidCulture,
    enemies: 4,
    friends: 3,
    complications: 4,
    things: 3,
    places: 4,
  },
  [worldTagKeys.risingHegemon]: {
    key: worldTagKeys.risingHegemon,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.ritualCombat]: {
    key: worldTagKeys.ritualCombat,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 4,
    places: 3,
  },
  [worldTagKeys.robots]: {
    key: worldTagKeys.robots,
    enemies: 4,
    friends: 3,
    complications: 4,
    things: 4,
    places: 3,
  },
  [worldTagKeys.seagoingCities]: {
    key: worldTagKeys.seagoingCities,
    enemies: 4,
    friends: 4,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.sealedMenace]: {
    key: worldTagKeys.sealedMenace,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.secretMasters]: {
    key: worldTagKeys.secretMasters,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.sectarians]: {
    key: worldTagKeys.sectarians,
    enemies: 3,
    friends: 4,
    complications: 5,
    things: 3,
    places: 4,
  },
  [worldTagKeys.seismicInstability]: {
    key: worldTagKeys.seismicInstability,
    enemies: 4,
    friends: 3,
    complications: 4,
    things: 4,
    places: 4,
  },
  [worldTagKeys.shackledWorld]: {
    key: worldTagKeys.shackledWorld,
    enemies: 4,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.societalDespair]: {
    key: worldTagKeys.societalDespair,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.soleSupplier]: {
    key: worldTagKeys.soleSupplier,
    enemies: 3,
    friends: 4,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.tabooTreasure]: {
    key: worldTagKeys.tabooTreasure,
    enemies: 4,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.terraformFailure]: {
    key: worldTagKeys.terraformFailure,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.theocracy]: {
    key: worldTagKeys.theocracy,
    enemies: 4,
    friends: 4,
    complications: 4,
    things: 4,
    places: 4,
  },
  [worldTagKeys.tombWorld]: {
    key: worldTagKeys.tombWorld,
    enemies: 4,
    friends: 4,
    complications: 4,
    things: 4,
    places: 5,
  },
  [worldTagKeys.tradeHub]: {
    key: worldTagKeys.tradeHub,
    enemies: 4,
    friends: 4,
    complications: 4,
    things: 4,
    places: 4,
  },
  [worldTagKeys.tyranny]: {
    key: worldTagKeys.tyranny,
    enemies: 5,
    friends: 4,
    complications: 4,
    things: 3,
    places: 4,
  },

  


  [worldTagKeys.unbrakedAi]: {
    key: worldTagKeys.unbrakedAi,
    name: 'Unbraked AI',
    description:
      'Artificial intelligences are costly and difficult to create, requiring a careful sequence of “growth stages” in order to bring them to sentience before artificial limits on cognition speed and learning development are installed. These “brakes” prevent runaway cognition metastasis. This world has an “unbraked AI” on it, probably with a witting or unwitting corps of servants. Unbraked AIs are quite insane, but they learn and reason with a speed impossible for humans, and can demonstrate a truly distressing subtlety.',
    'misc.enemies': [
      'AI cultist',
      'maltech researcher',
      'government official dependent on the AI',
    ],
    'misc.friends': ['perimeter agent', 'AI researcher', 'braked AI'],
    'misc.complications': [
      "the AI's presence is unknown to the locals",
      'the locals depend on the AI for some vital service',
      'the AI appears to be harmless',
      "the AI has fixated on the group's ship's computer",
      'the AI wants transport offworld',
    ],
    'misc.things': [
      'the room-sized AI core itself',
      'maltech research files',
      'perfectly tabulated blackmail on government officials',
      'pretech computer circuitry',
    ],
    'misc.places': [
      'municipal computing banks',
      'cult compound',
      'repair center',
      'ancient hardcopy library',
    ],
  },
  [worldTagKeys.urbanizedSurface]: {
    key: worldTagKeys.urbanizedSurface,
    name: 'Urbanized Surface',
    description:
      "The world's land area is covered with buildings that extend downward for multiple levels. Such worlds either have a population in the trillions, extremely little land area, or are largely-abandoned due to some past catastrophe. Agriculture and resource extraction are part of the urban complex, and there may be an advanced maintenance system that may not be entirely under the control of present natives.",
    'misc.enemies': [
      'maintenance AI that hates outsiders',
      'tyrant of a habitation block',
      'deep-dwelling prophet who considers "the sky" a blasphemy to be quelled',
    ],
    'misc.friends': [
      'local yearning for wild spaces',
      'grubby urchin of the underlevels',
      'harried engineer trying to maintain ancient works',
      'grizzled hab cop',
    ],
    'misc.complications': [
      'the urban blocks are needed to survive the environment',
      'the blocks were part of an ancient device of world-spanning size',
      'the blocks require constant maintenance to avoid dangerous types of decay',
    ],
    'misc.things': [
      'massively efficient power source',
      'map of the secret ways of a zone',
      'passkey into restricted hab block areas',
    ],
    'misc.places': [
      'giant hab block now devoid of inhabitants',
      'chemical-reeking underway',
      'seawater mine full of salt and massive flowing channels',
    ],
  },
  [worldTagKeys.utopia]: {
    key: worldTagKeys.utopia,
    name: 'Utopia',
    description:
      'Natural and social conditions on this world have made it a paradise for its inhabitants, a genuine utopia of happiness and fulfillment. This is normally the result of drastic human engineering, including brain-gelding, neurochemical control, personality curbs, or complete "humanity" redefinitions. Even so, the natives are extremely happy with their lot, and may wish to extend that joy to poor, sad outsiders.',
    'misc.enemies': [
      'compassionate neurotherapist',
      'proselytizing native missionary to outsiders',
      'brutal tyrant who rules through inexorable happiness',
    ],
    'misc.friends': [
      'deranged malcontent',
      'bloody-handed guerilla leader of a rebellion of madmen',
      'outsider trying to find a way to reverse the utopian changes',
    ],
    'misc.complications': [
      'the natives really are deeply and contentedly happy with their altered lot',
      'the utopia produces something that attracts others',
      'the utopia works on converting outsiders through persuasion and generosity',
      "the utopia involves some sacrifice that's horrifying to non-members",
    ],
    'misc.things': [
      'portable device that applies the utopian change',
      'plans for a device that would destroy the utopia',
      'goods created joyfully by the locals',
    ],
    'misc.places': [
      'plaza full of altered humans',
      'social ritual site',
      'secret office where "normal" humans rule',
    ],
  },
  [worldTagKeys.warlords]: {
    key: worldTagKeys.warlords,
    name: 'Warlords',
    description:
      'The world is plagued by warlords. Numerous powerful men and women control private armies sufficiently strong to cow whatever local government may exist. On the lands they claim, their word is law. Most spend their time oppressing their own subjects and murderously pillaging those of their neighbors. Most like to wrap themselves in the mantle of ideology, religious fervor, or an ostensibly legitimate right to rule.',
    'misc.enemies': [
      'warlord',
      'avaricious lieutenant',
      'expensive assassin',
      'aspiring minion',
    ],
    'misc.friends': [
      'Vengeful commoner',
      'government military officer',
      'humanitarian aid official',
      'village priest',
    ],
    'misc.complications': [
      'the warlords are willing to cooperate to fight mutual threats',
      'the warlords favor specific religions or races over others',
      'the warlords are using substantially more sophisticated tech than others',
      'some of the warlords are better rulers than the government',
    ],
    'misc.things': [
      'weapons cache, Buried plunder',
      "a warlord's personal battle harness",
      'captured merchant shipping',
    ],
    'misc.places': [
      'gory battlefield',
      'burnt-out village',
      'barbaric warlord palace',
      'squalid refugee camp',
    ],
  },
  [worldTagKeys.xenophiles]: {
    key: worldTagKeys.xenophiles,
    name: 'Xenophiles',
    description:
      'The natives of this world are fast friends with a particular alien race. The aliens may have saved the planet at some point in the past, or awed the locals with superior tech or impressive cultural qualities. The aliens might even be the ruling class on the planet.',
    'misc.enemies': [
      'offworld xenophobe',
      'suspicious alien leader',
      'xenocultural imperialist',
    ],
    'misc.friends': [
      'benevolent alien',
      'native malcontent',
      'gone-native offworlder',
    ],
    'misc.complications': [
      'the enthusiasm is due to alien psionics or tech',
      'the enthusiasm is based on a lie, The aliens strongly dislike their “groupies”',
      'the aliens feel obliged to rule humanity for its own good',
      'humans badly misunderstand the aliens',
    ],
    'misc.things': [
      'hybrid alien-human tech',
      'exotic alien crafts',
      'sophisticated xenolinguistic and xenocultural research data',
    ],
    'misc.places': [
      'alien district',
      'alien-influenced human home',
      'cultural festival celebrating alien artist',
    ],
  },
  [worldTagKeys.xenophobes]: {
    key: worldTagKeys.xenophobes,
    name: 'Xenophobes',
    description:
      'The natives are intensely averse to dealings with outworlders. Whether through cultural revulsion, fear of tech contamination, or a genuine immunodeficiency, the locals shun foreigners from offworld and refuse to have anything to do with them beyond the bare necessities of contact. Trade may or may not exist on this world, but if it does, it is almost certainly conducted by a caste of untouchables and outcasts.',
    'misc.enemies': [
      'revulsed local ruler',
      'native convinced some wrong was done to him',
      'cynical demagogue',
    ],
    'misc.friends': [
      'curious native',
      'exiled former ruler',
      'local desperately seeking outworlder help',
    ],
    'misc.complications': [
      'the natives are symptomless carriers of a contagious and dangerous disease',
      'the natives are exceptionally vulnerable to offworld diseases',
      'the natives require elaborate purification rituals after speaking to an offworlder or touching them',
      'the local ruler has forbidden any mercantile dealings with outworlders',
    ],
    'misc.things': [
      'jealously-guarded precious relic',
      'local product under export ban',
      'esoteric local technology',
    ],
    'misc.places': [
      'sealed treaty port',
      'public ritual not open to outsiders',
      'outcaste slum home',
    ],
  },
  [worldTagKeys.zombies]: {
    key: worldTagKeys.zombies,
    name: 'Zombies',
    description:
      'This menace may not take the form of shambling corpses, but some disease, alien artifact, or crazed local practice produces men and women with habits similar to those of murderous cannibal undead. These outbreaks may be regular elements in local society, either provoked by some malevolent creators or the consequence of some local condition.',
    'misc.enemies': [
      'soulless maltech biotechnology cult',
      'sinister governmental agent',
      'crazed zombie cultist',
    ],
    'misc.friends': [
      'survivor of an outbreak',
      'doctor searching for a cure',
      'rebel against the secret malefactors',
    ],
    'misc.complications': [
      'the zombies retain human intelligence',
      'the zombies can be cured',
      'the process is voluntary among devotees',
      'the condition is infectious',
    ],
    'misc.things': [
      'cure for the condition',
      'alien artifact that causes it',
      "details of the cult's conversion process",
    ],
    'misc.places': [
      'house with boarded-up windows',
      'dead city',
      'fortified bunker that was overrun from within',
    ],
  },
};
