export const worldTagKeys = {
  abandonedColony: 'abandonedColony',
  alienRuins: 'alienRuins',
  alteredHumanity: 'alteredHumanity',
  anarchists: 'anarchists',
  anthropomorphs: 'anthropomorphs',
  area51: 'area51',
  badlandsWorld: 'badlandsWorld',
  battleground: 'battleground',
  beastmasters: 'beastmasters',
  bubbleCities: 'bubbleCities',
  cheapLife: 'cheapLife',
  civilWar: 'civilWar',
  coldWar: 'coldWar',
  colonizedPopulation: 'colonizedPopulation',
  culturalPower: 'culturalPower',
  cybercommunists: 'cybercommunists',
  cyborgs: 'cyborgs',
  cyclicalDoom: 'cyclicalDoom',
  desertWorld: 'desertWorld',
  doomedWorld: 'doomedWorld',
  dyingRace: 'dyingRace',
  eugenicCult: 'eugenicCult',
  exchangeConsulate: 'exchangeConsulate',
  fallenHegemon: 'fallenHegemon',
  feralWorld: 'feralWorld',
  flyingCities: 'flyingCities',
  forbiddenTech: 'forbiddenTech',
  formerWarriors: 'formerWarriors',
  freakGeology: 'freakGeology',
  freakWeather: 'freakWeather',
  friendlyFoe: 'friendlyFoe',
  goldRush: 'goldRush',
  greatWork: 'greatWork',
  hatred: 'hatred',
  heavyIndustry: 'heavyIndustry',
  heavyMining: 'heavyMining',
  hivemind: 'hivemind',
  holyWar: 'holyWar',
  hostileBiosphere: 'hostileBiosphere',
  hostileSpace: 'hostileSpace',
  immortals: 'immortals',
  localSpecialty: 'localSpecialty',
  localTech: 'localTech',
  majorSpaceyard: 'majorSpaceyard',
  mandarinate: 'mandarinate',
  mandateBase: 'mandateBase',
  maneaters: 'maneaters',
  megacorps: 'megacorps',
  mercenaries: 'mercenaries',
  minimalContact: 'minimalContact',
  misandryMisogyny: 'misandryMisogyny',
  nightWorld: 'nightWorld',
  nomads: 'nomads',
  oceanicWorld: 'oceanicWorld',
  outOfContact: 'outOfContact',
  outpostWorld: 'outpostWorld',
  perimeterAgency: 'perimeterAgency',
  pilgrimageSite: 'pilgrimageSite',
  pleasureWorld: 'pleasureWorld',
  policeState: 'policeState',
  postScarcity: 'postScarcity',
  preceptorArchive: 'preceptorArchive',
  pretechCultists: 'pretechCultists',
  primitiveAliens: 'primitiveAliens',
  prisonPlanet: 'prisonPlanet',
  psionicsAcademy: 'psionicsAcademy',
  psionicsFear: 'psionicsFear',
  psionicsWorship: 'psionicsWorship',
  quarantinedWorld: 'quarantinedWorld',
  radioactiveWorld: 'radioactiveWorld',
  refugees: 'refugees',
  regionalHegemon: 'regionalHegemon',
  restrictiveLaws: 'restrictiveLaws',
  revanchists: 'revanchists',
  revolutionaries: 'revolutionaries',
  rigidCulture: 'rigidCulture',
  risingHegemon: 'risingHegemon',
  ritualCombat: 'ritualCombat',
  robots: 'robots',
  seagoingCities: 'seagoingCities',
  sealedMenace: 'sealedMenace',
  secretMasters: 'secretMasters',
  sectarians: 'sectarians',
  seismicInstability: 'seismicInstability',
  shackledWorld: 'shackledWorld',
  societalDespair: 'societalDespair',
  soleSupplier: 'soleSupplier',
  tabooTreasure: 'tabooTreasure',
  terraformFailure: 'terraformFailure',
  theocracy: 'theocracy',
  tombWorld: 'tombWorld',
  tradeHub: 'tradeHub',
  tyranny: 'tyranny',
  unbrakedAi: 'unbrakedAi',
  urbanizedSurface: 'urbanizedSurface',
  utopia: 'utopia',
  warlords: 'warlords',
  xenophiles: 'xenophiles',
  xenophobes: 'xenophobes',
  zombies: 'zombies',
};

export default {
    [worldTagKeys.abandonedColony]: {
    key: worldTagKeys.abandonedColony,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
   [worldTagKeys.alienRuins]: {
    key: worldTagKeys.alienRuins,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 4,
    places: 4,
  },
  [worldTagKeys.alteredHumanity]: {
    key: worldTagKeys.alteredHumanity,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 4,
    places: 3,
  },
  [worldTagKeys.anarchists]: {
    key: worldTagKeys.anarchists,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.anthropomorphs]: {
    key: worldTagKeys.anthropomorphs,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.area51]: {
    key: worldTagKeys.area51,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.badlandsWorld]: {
    key: worldTagKeys.badlandsWorld,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.battleground]: {
    key: worldTagKeys.battleground,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.beastmasters]: {
    key: worldTagKeys.beastmasters,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.bubbleCities]: {
    key: worldTagKeys.bubbleCities,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 4,
  },
  [worldTagKeys.cheapLife]: {
    key: worldTagKeys.cheapLife,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.civilWar]: {
    key: worldTagKeys.civilWar,
    enemies: 5,
    friends: 3,
    complications: 3,
    things: 4,
    places: 4,
  },
  [worldTagKeys.coldWar]: {
    key: worldTagKeys.coldWar,
    enemies: 3,
    friends: 4,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.colonizedPopulation]: {
    key: worldTagKeys.colonizedPopulation,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.culturalPower]: {
    key: worldTagKeys.culturalPower,
    enemies: 4,
    friends: 4,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.cybercommunists]: {
    key: worldTagKeys.cybercommunists,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.cyborgs]: {
    key: worldTagKeys.cyborgs,
    enemies: 4,
    friends: 3,
    complications: 3,
    things: 4,
    places: 3,
  },
  [worldTagKeys.cyclicalDoom]: {
    key: worldTagKeys.cyclicalDoom,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.desertWorld]: {
    key: worldTagKeys.desertWorld,
    enemies: 5,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.doomedWorld]: {
    key: worldTagKeys.doomedWorld,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 4,
    places: 3,
  },
  [worldTagKeys.dyingRace]: {
    key: worldTagKeys.dyingRace,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.eugenicCult]: {
    key: worldTagKeys.eugenicCult,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 4,
    places: 3,
  },
  [worldTagKeys.exchangeConsulate]: {
    key: worldTagKeys.exchangeConsulate,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.fallenHegemon]: {
    key: worldTagKeys.fallenHegemon,
    enemies: 4,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.feralWorld]: {
    key: worldTagKeys.feralWorld,
    enemies: 5,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.flyingCities]: {
    key: worldTagKeys.flyingCities,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.forbiddenTech]: {
    key: worldTagKeys.forbiddenTech,
    enemies: 3,
    friends: 4,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.formerWarriors]: {
    key: worldTagKeys.formerWarriors,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.freakGeology]: {
    key: worldTagKeys.freakGeology,
    enemies: 2,
    friends: 3,
    complications: 3,
    things: 3,
    places: 2,
  },
  [worldTagKeys.freakWeather]: {
    key: worldTagKeys.freakWeather,
    enemies: 3,
    friends: 2,
    complications: 2,
    things: 3,
    places: 3,
  },
  [worldTagKeys.friendlyFoe]: {
    key: worldTagKeys.friendlyFoe,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.goldRush]: {
    key: worldTagKeys.goldRush,
    enemies: 4,
    friends: 4,
    complications: 3,
    things: 3,
    places: 4,
  },
  [worldTagKeys.greatWork]: {
    key: worldTagKeys.greatWork,
    enemies: 4,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.hatred]: {
    key: worldTagKeys.hatred,
    enemies: 2,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.heavyIndustry]: {
    key: worldTagKeys.heavyIndustry,
    enemies: 4,
    friends: 3,
    complications: 4,
    things: 3,
    places: 4,
  },
  [worldTagKeys.heavyMining]: {
    key: worldTagKeys.heavyMining,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.hivemind]: {
    key: worldTagKeys.hivemind,
    enemies: 3,
    friends: 3,
    complications: 5,
    things: 3,
    places: 3,
  },
  [worldTagKeys.holyWar]: {
    key: worldTagKeys.holyWar,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.hostileBiosphere]: {
    key: worldTagKeys.hostileBiosphere,
    enemies: 4,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.hostileSpace]: {
    key: worldTagKeys.hostileSpace,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.immortals]: {
    key: worldTagKeys.immortals,
    enemies: 3,
    friends: 2,
    complications: 5,
    things: 3,
    places: 3,
  },
  [worldTagKeys.localSpecialty]: {
    key: worldTagKeys.localSpecialty,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.localTech]: {
    key: worldTagKeys.localTech,
    enemies: 4,
    friends: 3,
    complications: 4,
    things: 4,
    places: 3,
  },
  [worldTagKeys.majorSpaceyard]: {
    key: worldTagKeys.majorSpaceyard,
    enemies: 4,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.mandarinate]: {
    key: worldTagKeys.mandarinate,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.mandateBase]: {
    key: worldTagKeys.mandateBase,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.maneaters]: {
    key: worldTagKeys.maneaters,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.megacorps]: {
    key: worldTagKeys.megacorps,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 4,
    places: 3,
  },
  [worldTagKeys.mercenaries]: {
    key: worldTagKeys.mercenaries,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.minimalContact]: {
    key: worldTagKeys.minimalContact,
    enemies: 3,
    friends: 4,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.misandryMisogyny]: {
    key: worldTagKeys.misandryMisogyny,
    enemies: 3,
    friends: 4,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.nightWorld]: {
    key: worldTagKeys.nightWorld,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.nomads]: {
    key: worldTagKeys.nomads,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.oceanicWorld]: {
    key: worldTagKeys.oceanicWorld,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 4,
  },
  [worldTagKeys.outOfContact]: {
    key: worldTagKeys.outOfContact,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.outpostWorld]: {
    key: worldTagKeys.outpostWorld,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 4,
  },
  [worldTagKeys.perimeterAgency]: {
    key: worldTagKeys.perimeterAgency,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 4,
  },
  [worldTagKeys.pilgrimageSite]: {
    key: worldTagKeys.pilgrimageSite,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.pleasureWorld]: {
    key: worldTagKeys.pleasureWorld,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.policeState]: {
    key: worldTagKeys.policeState,
    enemies: 3,
    friends: 4,
    complications: 3,
    things: 3,
    places: 4,
  },
  [worldTagKeys.postScarcity]: {
    key: worldTagKeys.postScarcity,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.preceptorArchive]: {
    key: worldTagKeys.preceptorArchive,
    enemies: 4,
    friends: 4,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.pretechCultists]: {
    key: worldTagKeys.pretechCultists,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.primitiveAliens]: {
    key: worldTagKeys.primitiveAliens,
    enemies: 4,
    friends: 4,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.prisonPlanet]: {
    key: worldTagKeys.prisonPlanet,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.psionicsAcademy]: {
    key: worldTagKeys.psionicsAcademy,
    enemies: 4,
    friends: 3,
    complications: 5,
    things: 3,
    places: 4,
  },
  [worldTagKeys.psionicsFear]: {
    key: worldTagKeys.psionicsFear,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.psionicsWorship]: {
    key: worldTagKeys.psionicsWorship,
    enemies: 4,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.quarantinedWorld]: {
    key: worldTagKeys.quarantinedWorld,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.radioactiveWorld]: {
    key: worldTagKeys.radioactiveWorld,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 4,
  },
  [worldTagKeys.refugees]: {
    key: worldTagKeys.refugees,
    enemies: 3,
    friends: 3,
    complications: 5,
    things: 4,
    places: 3,
  },
  [worldTagKeys.regionalHegemon]: {
    key: worldTagKeys.regionalHegemon,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 4,
  },
  [worldTagKeys.restrictiveLaws]: {
    key: worldTagKeys.restrictiveLaws,
    enemies: 4,
    friends: 3,
    complications: 4,
    things: 3,
    places: 4,
  },
  [worldTagKeys.revanchists]: {
    key: worldTagKeys.revanchists,
    enemies: 4,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.revolutionaries]: {
    key: worldTagKeys.revolutionaries,
    enemies: 3,
    friends: 3,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.rigidCulture]: {
    key: worldTagKeys.rigidCulture,
    enemies: 4,
    friends: 3,
    complications: 4,
    things: 3,
    places: 4,
  },
  [worldTagKeys.risingHegemon]: {
    key: worldTagKeys.risingHegemon,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },
  [worldTagKeys.ritualCombat]: {
    key: worldTagKeys.ritualCombat,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 4,
    places: 3,
  },
  [worldTagKeys.robots]: {
    key: worldTagKeys.robots,
    enemies: 4,
    friends: 3,
    complications: 4,
    things: 4,
    places: 3,
  },
  [worldTagKeys.seagoingCities]: {
    key: worldTagKeys.seagoingCities,
    enemies: 4,
    friends: 4,
    complications: 4,
    things: 3,
    places: 3,
  },
  [worldTagKeys.sealedMenace]: {
    key: worldTagKeys.sealedMenace,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 3,
    places: 3,
  },






  [worldTagKeys.secretMasters]: {
    key: worldTagKeys.secretMasters,
    name: 'Secret Masters',
    description:
      "The world is actually run by a hidden cabal, acting through their catspaws in the visible government. For one reason or another, this group finds it imperative that they not be identified by outsiders, and in some cases even the planet's own government may not realize that they're actually being manipulated by hidden masters.",
    'misc.enemies': [
      'an agent of the cabal',
      'government official who wants no questions asked',
      'willfully blinded local',
    ],
    'misc.friends': [
      'paranoid conspiracy theorist',
      'machiavellian gamesman within the cabal',
      'interstellar investigator',
    ],
    'misc.complications': [
      'the secret masters have a benign reason for wanting secrecy',
      'the cabal fights openly amongst itself',
      'the cabal is recruiting new members',
    ],
    'misc.things': [
      'a dossier of secrets on a government official',
      'a briefcase of unmarked credit notes',
      'the identity of a cabal member',
    ],
    'misc.places': [
      'smoke-filled room',
      'shadowy alleyway',
      'secret underground bunker',
    ],
  },
  [worldTagKeys.sectarians]: {
    key: worldTagKeys.sectarians,
    name: 'Sectarians',
    description:
      'The world is torn by violent disagreement between sectarians of a particular faith. Each views the other as a damnable heresy in need of extirpation. Local government may be able to keep open war from breaking out, but the poisonous hatred divides communities. The nature of the faith may be religious, or it may be based on some secular ideology.',
    'misc.enemies': [
      'paranoid believer',
      'native convinced the party is working for the other side',
      'absolutist ruler',
    ],
    'misc.friends': [
      'reformist clergy',
      'local peacekeeping official',
      'offworld missionary',
      'exhausted ruler',
    ],
    'misc.complications': [
      'the conflict has more than two sides',
      'the sectarians hate each other for multiple reasons',
      'the sectarians must cooperate or else life on this world is imperiled',
      'the sectarians hate outsiders more than they hate each other',
      'the differences in sects are incomprehensible to an outsider',
    ],
    'misc.things': [
      'ancient holy book',
      'incontrovertible proof',
      'offering to a local holy man',
    ],
    'misc.places': [
      'sectarian battlefield',
      'crusading temple',
      "philosopher's salon",
      'bitterly divided village',
    ],
  },
  [worldTagKeys.seismicInstability]: {
    key: worldTagKeys.seismicInstability,
    name: 'Seismic Instability',
    description:
      'The local land masses are remarkably unstable, and regular earthquakes rack the surface. Local construction is either advanced enough to sway and move with the vibrations or primitive enough that it is easily rebuilt. Severe volcanic activity may be part of the instability.',
    'misc.enemies': [
      'earthquake cultist',
      'hermit seismologist',
      'burrowing native life form',
      'earthquake-inducing saboteur',
    ],
    'misc.friends': [
      'experimental construction firm owner',
      'adventurous volcanologist',
      'geothermal prospector',
    ],
    'misc.complications': [
      'the earthquakes are caused by malfunctioning pretech terraformers',
      "they're caused by alien technology",
      "they're restrained by alien technology that is being plundered by offworlders",
      'the earthquakes are used to generate enormous amounts of energy',
    ],
    'misc.things': [
      'earthquake generator',
      'earthquake suppressor',
      'mineral formed at the core of the world',
      'earthquake-proof building schematics',
    ],
    'misc.places': [
      'volcanic caldera',
      'village during an earthquake',
      'mud slide',
      'earthquake opening superheated steam fissures',
    ],
  },
  [worldTagKeys.shackledWorld]: {
    key: worldTagKeys.shackledWorld,
    name: 'Shackled World',
    description:
      'This world is being systematically contained by an outside power. Some ancient autonomous defense grid, robot law enforcement, alien artifact, or other force is preventing the locals from developing certain technology, or using certain devices, or perhaps from developing interstellar flight. This limit may or may not apply to offworlders; in the former case, the PCs may have to figure out a way to beat the shackles simply to escape the world.',
    'misc.enemies': [
      'passionless jailer-AI',
      'paranoid military grid AI',
      'robot overlord',
      'enigmatic alien master',
    ],
    'misc.friends': [
      'struggling local researcher',
      'offworlder trapped here',
      'scientist with a plan to break the chains',
    ],
    'misc.complications': [
      'the shackles come off for certain brief windows of time',
      'the locals think the shackles are imposed by God',
      'an outside power greatly profits from the shackles',
      'the rulers are exempt from the shackles',
    ],
    'misc.things': [
      'keycode to bypass the shackle',
      'tech shielded from the shackle',
      'exportable version of the shackle that can affect other worlds',
    ],
    'misc.places': [
      'grim high-tech control center',
      'factory full of workaround tech',
      'temple to the power or entity that imposed the shackle',
    ],
  },
  [worldTagKeys.societalDespair]: {
    key: worldTagKeys.societalDespair,
    name: 'Societal Despair',
    description:
      "The world's dominant society has lost faith in itself. Whether through some all-consuming war, great catastrophe, overwhelming outside culture, or religious collapse, the natives no longer believe in their old values, and search desperately for something new. Fierce conflict often exists between the last believers in the old dispensation and the nihilistic or searching disciples of the new age.",
    'misc.enemies': [
      'zealot who blames outsiders for the decay',
      'nihilistic warlord',
      'offworlder looking to exploit the local despair',
    ],
    'misc.friends': [
      'struggling messenger of a new way',
      'valiant paragon of a fading tradition',
      'local going through the motions of serving a now-irrelevant role',
    ],
    'misc.complications': [
      'a massive war discredited all the old values',
      'outside powers are working to erode societal confidence for their own benefit',
      'a local power is profiting greatly from the despair',
      'the old ways were meant to aid survival on this world and their passing is causing many new woes',
    ],
    'misc.things': [
      'relic that would inspire a renaissance',
      'art that would inspire new ideas',
      'priceless artifact of a now-scorned belief',
    ],
    'misc.places': [
      'empty temple',
      'crowded den of obliviating vice',
      'smoky hall full of frantic speakers',
    ],
  },
  [worldTagKeys.soleSupplier]: {
    key: worldTagKeys.soleSupplier,
    name: 'Sole Supplier',
    description:
      "Some extremely important resource is exported from this world and this world alone. It's unlikely that the substance is critical for building spike drives unless this world is also the first to begin interstellar flight, but it may be critical to other high-tech processes or devices. The locals make a large amount of money off this trade and control of it is of critical importance to the planet's rulers, and potentially to outside powers.",
    'misc.enemies': [
      'resource oligarch, Ruthless smuggler',
      'resource-controlling warlord',
      'foreign agent seeking to subvert local government',
    ],
    'misc.friends': [
      'doughty resource miner',
      'researcher trying to synthesize the stuff',
      'small-scale resource producer',
      'harried starport trade overseer',
    ],
    'misc.complications': [
      'the substance is slow poison to process',
      'the substance is created by hostile alien natives',
      'the substance is very easy to smuggle in usable amounts',
      'only the natives have the genes or tech to extract it effectively',
    ],
    'misc.things': [
      'cache of processed resource',
      'trade permit to buy a load of it',
      'a shipment of nigh-undetectably fake substance',
    ],
    'misc.places': [
      'bustling resource extraction site',
      'opulent palace built with resource money',
      'lazy town square where everyone lives on resource payments',
    ],
  },
  [worldTagKeys.tabooTreasure]: {
    key: worldTagKeys.tabooTreasure,
    name: 'Taboo Treasure',
    description:
      'The natives here produce something that is both fabulously valuable and strictly forbidden elsewhere in the sector. It may be a lethally addictive drug, forbidden gengineering tech, vat-grown "perfect slaves", or a useful substance that can only be made through excruciating human suffering. This treasure is freely traded on the world, but bringing it elsewhere is usually an invitation to a long prison stay or worse.',
    'misc.enemies': [
      'maker of a vile commodity',
      'smuggler for a powerful offworlder',
      'depraved offworlder here for "fun"',
      'local warlord who controls the treasure',
    ],
    'misc.friends': [
      'reformer seeking to end its use',
      'innovator trying to repurpose the treasure in innocent ways',
      'wretched addict unwillingly prey to the treasure',
    ],
    'misc.complications': [
      'the treasure is extremely hard to smuggle',
      'its use visibly marks a user',
      'the natives consider it for their personal use only',
    ],
    'misc.things': [
      'load of the forbidden good',
      'smuggling tech that could hide the good perfectly',
      'blackmail data on offworld buyers of the good',
    ],
    'misc.places': [
      'den where the good is used',
      'market selling the good to locals and a few outsiders',
      'factory or processing area where the good is created',
    ],
  },
  [worldTagKeys.terraformFailure]: {
    key: worldTagKeys.terraformFailure,
    name: 'Terraform Failure',
    description:
      "This world was marginal for human habitation when it was discovered, but the Mandate or the early government put in pretech terraforming engines to correct its more extreme qualities. The terraforming did not entirely work, either failing of its own or suffering the destruction of the engines during the Silence. The natives are only partly adapted to the world's current state, and struggle with the environment.",
    'misc.enemies': [
      'brutal ruler who cares only for their people',
      'offworlder trying to loot the damaged engines',
      'warlord trying to seize limited habitable land',
    ],
    'misc.friends': [
      'local trying to fix the engines',
      'offworlder student of the engines',
      'world-wise native survivor',
    ],
    'misc.complications': [
      'the engines produced too much of something instead of too little',
      'the engines were hijacked by aliens with different preferences',
      'it was discovered that an Earth-like environment would eventually cause a catastrophic disaster',
    ],
    'misc.things': [
      'parts to repair or restore the engines',
      'lootable pretech fragments',
      'valuable local tech devised to cope with the world',
    ],
    'misc.places': [
      'zone of tolerable gravity or temperature',
      'native settlement built to cope with the environment',
      'massive ruined terraforming engine',
    ],
  },
  [worldTagKeys.theocracy]: {
    key: worldTagKeys.theocracy,
    name: 'Theocracy',
    description:
      'The planet is ruled by the priesthood of the predominant religion or ideology. The rest of the locals may or may not be terribly pious, but the clergy have the necessary military strength, popular support or control of resources to maintain their rule. Alternative faiths or incompatible ideologies are likely to be both illegal and socially unacceptable.',
    'misc.enemies': [
      'decadent priest-ruler',
      'zealous inquisitor',
      'relentless proselytizer',
      'True Believer',
    ],
    'misc.friends': [
      'heretic',
      'offworld theologian',
      'atheistic merchant',
      'desperate commoner',
    ],
    'misc.complications': [
      'the theocracy actually works well',
      'the theocracy is decadent and hated by the common folk',
      'the theocracy is divided into mutually hostile sects',
      'the theocracy is led by aliens',
    ],
    'misc.things': [
      'precious holy text',
      "martyr's bones",
      'secret church records',
      'ancient church treasures',
    ],
    'misc.places': [
      'glorious temple',
      'austere monastery',
      'academy for ideological indoctrination',
      'decadent pleasure-cathedral',
    ],
  },
  [worldTagKeys.tombWorld]: {
    key: worldTagKeys.tombWorld,
    name: 'Tomb World',
    description:
      'Tomb worlds are planets that were once inhabited by humans before the Silence. The sudden collapse of the jump gate network and the inability to bring in the massive food supplies required by the planet resulted in starvation, warfare, and death. Most tomb worlds are naturally hostile to human habitation and could not raise sufficient crops to maintain life. The few hydroponic facilities were usually destroyed in the fighting, and all that is left now are ruins, bones, and silence.',
    'misc.enemies': [
      'demented survivor tribe chieftain',
      'avaricious scavenger',
      'automated defense system',
      'native predator',
    ],
    'misc.friends': [
      'scavenger fleet captain',
      'archaeologist',
      'salvaging historian',
      'xenophilic native survivor',
    ],
    'misc.complications': [
      'the ruins are full of booby-traps left by the final inhabitants',
      "the world's atmosphere quickly degrades anything in an opened building",
      'a handful of desperate natives survived the Silence',
      'the structures are unstable and collapsing',
    ],
    'misc.things': [
      'lost pretech equipment',
      'tech caches',
      'stores of unused munitions',
      'ancient historical data',
    ],
    'misc.places': [
      'crumbling hive-city',
      'city square carpeted in bones',
      'ruined hydroponic facility',
      "cannibal tribe's lair",
      'dead orbital jump gate',
    ],
  },
  [worldTagKeys.tradeHub]: {
    key: worldTagKeys.tradeHub,
    name: 'Trade Hub',
    description:
      'This world is a major crossroads for local interstellar trade. It is well-positioned at the nexus of several short-drill trade routes, and has facilities for easy transfer of valuable cargoes and the fueling and repairing of starships. The natives are accustomed to outsiders, and a polyglot mass of people from every nearby world can be found trading here.',
    'misc.enemies': [
      'cheating merchant',
      'thieving dockworker',
      'commercial spy',
      'corrupt customs official',
    ],
    'misc.friends': [
      'rich tourist',
      'hardscrabble free trader',
      'merchant prince in need of catspaws',
      'friendly spaceport urchin',
    ],
    'misc.complications': [
      'an outworlder faction schemes to seize the trade hub',
      "saboteurs seek to blow up a rival's warehouses",
      'enemies are blockading the trade routes',
      'pirates lace the hub with spies',
    ],
    'misc.things': [
      "voucher for a warehouse's contents",
      'insider trading information',
      'case of precious offworld pharmaceuticals',
      'box of legitimate tax stamps indicating customs dues have been paid',
    ],
    'misc.places': [
      'raucous bazaar',
      'elegant restaurant',
      'spaceport teeming with activity',
      'foggy street lined with warehouses',
    ],
  },
  [worldTagKeys.tyranny]: {
    key: worldTagKeys.tyranny,
    name: 'Tyranny',
    description:
      'The local government is brutal and indifferent to the will of the people. Laws may or may not exist, but the only one that matters is the whim of the rulers on any given day. Their minions swagger through the streets while the common folk live in terror of their appetites. The only people who stay wealthy are friends and servants of the ruling class.',
    'misc.enemies': [
      'debauched autocrat',
      'sneering bully-boy',
      'soulless government official',
      'occupying army officer',
    ],
    'misc.friends': [
      'conspiring rebel',
      'oppressed merchant',
      'desperate peasant',
      'inspiring religious leader',
    ],
    'misc.complications': [
      'the tyrant rules with vastly superior technology',
      'the tyrant is a figurehead for a cabal of powerful men and women',
      'the people are resigned to their suffering',
      'the tyrant is hostile to “meddlesome outworlders”',
    ],
    'misc.things': [
      'plundered wealth',
      'beautiful toys of the elite',
      'regalia of rulership',
    ],
    'misc.places': [
      'impoverished village',
      'protest rally massacre',
      'decadent palace',
      'religious hospital for the indigent',
    ],
  },
  [worldTagKeys.unbrakedAi]: {
    key: worldTagKeys.unbrakedAi,
    name: 'Unbraked AI',
    description:
      'Artificial intelligences are costly and difficult to create, requiring a careful sequence of “growth stages” in order to bring them to sentience before artificial limits on cognition speed and learning development are installed. These “brakes” prevent runaway cognition metastasis. This world has an “unbraked AI” on it, probably with a witting or unwitting corps of servants. Unbraked AIs are quite insane, but they learn and reason with a speed impossible for humans, and can demonstrate a truly distressing subtlety.',
    'misc.enemies': [
      'AI cultist',
      'maltech researcher',
      'government official dependent on the AI',
    ],
    'misc.friends': ['perimeter agent', 'AI researcher', 'braked AI'],
    'misc.complications': [
      "the AI's presence is unknown to the locals",
      'the locals depend on the AI for some vital service',
      'the AI appears to be harmless',
      "the AI has fixated on the group's ship's computer",
      'the AI wants transport offworld',
    ],
    'misc.things': [
      'the room-sized AI core itself',
      'maltech research files',
      'perfectly tabulated blackmail on government officials',
      'pretech computer circuitry',
    ],
    'misc.places': [
      'municipal computing banks',
      'cult compound',
      'repair center',
      'ancient hardcopy library',
    ],
  },
  [worldTagKeys.urbanizedSurface]: {
    key: worldTagKeys.urbanizedSurface,
    name: 'Urbanized Surface',
    description:
      "The world's land area is covered with buildings that extend downward for multiple levels. Such worlds either have a population in the trillions, extremely little land area, or are largely-abandoned due to some past catastrophe. Agriculture and resource extraction are part of the urban complex, and there may be an advanced maintenance system that may not be entirely under the control of present natives.",
    'misc.enemies': [
      'maintenance AI that hates outsiders',
      'tyrant of a habitation block',
      'deep-dwelling prophet who considers "the sky" a blasphemy to be quelled',
    ],
    'misc.friends': [
      'local yearning for wild spaces',
      'grubby urchin of the underlevels',
      'harried engineer trying to maintain ancient works',
      'grizzled hab cop',
    ],
    'misc.complications': [
      'the urban blocks are needed to survive the environment',
      'the blocks were part of an ancient device of world-spanning size',
      'the blocks require constant maintenance to avoid dangerous types of decay',
    ],
    'misc.things': [
      'massively efficient power source',
      'map of the secret ways of a zone',
      'passkey into restricted hab block areas',
    ],
    'misc.places': [
      'giant hab block now devoid of inhabitants',
      'chemical-reeking underway',
      'seawater mine full of salt and massive flowing channels',
    ],
  },
  [worldTagKeys.utopia]: {
    key: worldTagKeys.utopia,
    name: 'Utopia',
    description:
      'Natural and social conditions on this world have made it a paradise for its inhabitants, a genuine utopia of happiness and fulfillment. This is normally the result of drastic human engineering, including brain-gelding, neurochemical control, personality curbs, or complete "humanity" redefinitions. Even so, the natives are extremely happy with their lot, and may wish to extend that joy to poor, sad outsiders.',
    'misc.enemies': [
      'compassionate neurotherapist',
      'proselytizing native missionary to outsiders',
      'brutal tyrant who rules through inexorable happiness',
    ],
    'misc.friends': [
      'deranged malcontent',
      'bloody-handed guerilla leader of a rebellion of madmen',
      'outsider trying to find a way to reverse the utopian changes',
    ],
    'misc.complications': [
      'the natives really are deeply and contentedly happy with their altered lot',
      'the utopia produces something that attracts others',
      'the utopia works on converting outsiders through persuasion and generosity',
      "the utopia involves some sacrifice that's horrifying to non-members",
    ],
    'misc.things': [
      'portable device that applies the utopian change',
      'plans for a device that would destroy the utopia',
      'goods created joyfully by the locals',
    ],
    'misc.places': [
      'plaza full of altered humans',
      'social ritual site',
      'secret office where "normal" humans rule',
    ],
  },
  [worldTagKeys.warlords]: {
    key: worldTagKeys.warlords,
    name: 'Warlords',
    description:
      'The world is plagued by warlords. Numerous powerful men and women control private armies sufficiently strong to cow whatever local government may exist. On the lands they claim, their word is law. Most spend their time oppressing their own subjects and murderously pillaging those of their neighbors. Most like to wrap themselves in the mantle of ideology, religious fervor, or an ostensibly legitimate right to rule.',
    'misc.enemies': [
      'warlord',
      'avaricious lieutenant',
      'expensive assassin',
      'aspiring minion',
    ],
    'misc.friends': [
      'Vengeful commoner',
      'government military officer',
      'humanitarian aid official',
      'village priest',
    ],
    'misc.complications': [
      'the warlords are willing to cooperate to fight mutual threats',
      'the warlords favor specific religions or races over others',
      'the warlords are using substantially more sophisticated tech than others',
      'some of the warlords are better rulers than the government',
    ],
    'misc.things': [
      'weapons cache, Buried plunder',
      "a warlord's personal battle harness",
      'captured merchant shipping',
    ],
    'misc.places': [
      'gory battlefield',
      'burnt-out village',
      'barbaric warlord palace',
      'squalid refugee camp',
    ],
  },
  [worldTagKeys.xenophiles]: {
    key: worldTagKeys.xenophiles,
    name: 'Xenophiles',
    description:
      'The natives of this world are fast friends with a particular alien race. The aliens may have saved the planet at some point in the past, or awed the locals with superior tech or impressive cultural qualities. The aliens might even be the ruling class on the planet.',
    'misc.enemies': [
      'offworld xenophobe',
      'suspicious alien leader',
      'xenocultural imperialist',
    ],
    'misc.friends': [
      'benevolent alien',
      'native malcontent',
      'gone-native offworlder',
    ],
    'misc.complications': [
      'the enthusiasm is due to alien psionics or tech',
      'the enthusiasm is based on a lie, The aliens strongly dislike their “groupies”',
      'the aliens feel obliged to rule humanity for its own good',
      'humans badly misunderstand the aliens',
    ],
    'misc.things': [
      'hybrid alien-human tech',
      'exotic alien crafts',
      'sophisticated xenolinguistic and xenocultural research data',
    ],
    'misc.places': [
      'alien district',
      'alien-influenced human home',
      'cultural festival celebrating alien artist',
    ],
  },
  [worldTagKeys.xenophobes]: {
    key: worldTagKeys.xenophobes,
    name: 'Xenophobes',
    description:
      'The natives are intensely averse to dealings with outworlders. Whether through cultural revulsion, fear of tech contamination, or a genuine immunodeficiency, the locals shun foreigners from offworld and refuse to have anything to do with them beyond the bare necessities of contact. Trade may or may not exist on this world, but if it does, it is almost certainly conducted by a caste of untouchables and outcasts.',
    'misc.enemies': [
      'revulsed local ruler',
      'native convinced some wrong was done to him',
      'cynical demagogue',
    ],
    'misc.friends': [
      'curious native',
      'exiled former ruler',
      'local desperately seeking outworlder help',
    ],
    'misc.complications': [
      'the natives are symptomless carriers of a contagious and dangerous disease',
      'the natives are exceptionally vulnerable to offworld diseases',
      'the natives require elaborate purification rituals after speaking to an offworlder or touching them',
      'the local ruler has forbidden any mercantile dealings with outworlders',
    ],
    'misc.things': [
      'jealously-guarded precious relic',
      'local product under export ban',
      'esoteric local technology',
    ],
    'misc.places': [
      'sealed treaty port',
      'public ritual not open to outsiders',
      'outcaste slum home',
    ],
  },
  [worldTagKeys.zombies]: {
    key: worldTagKeys.zombies,
    name: 'Zombies',
    description:
      'This menace may not take the form of shambling corpses, but some disease, alien artifact, or crazed local practice produces men and women with habits similar to those of murderous cannibal undead. These outbreaks may be regular elements in local society, either provoked by some malevolent creators or the consequence of some local condition.',
    'misc.enemies': [
      'soulless maltech biotechnology cult',
      'sinister governmental agent',
      'crazed zombie cultist',
    ],
    'misc.friends': [
      'survivor of an outbreak',
      'doctor searching for a cure',
      'rebel against the secret malefactors',
    ],
    'misc.complications': [
      'the zombies retain human intelligence',
      'the zombies can be cured',
      'the process is voluntary among devotees',
      'the condition is infectious',
    ],
    'misc.things': [
      'cure for the condition',
      'alien artifact that causes it',
      "details of the cult's conversion process",
    ],
    'misc.places': [
      'house with boarded-up windows',
      'dead city',
      'fortified bunker that was overrun from within',
    ],
  },
};
